### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "encounter_id_unique"

### ISSUE THREAD

**Issue by wjpvandenheuvel** [Brideau/pokelyzer#10]
Getting the following error when running latest Pokemongo [dev](https://github.com/AHAAAAAAA/PokemonGo-Map/commit/3ebb51ef48d73190e6171712c6395c119800fb35) after I have applied the 28st of July patch to Pokelyzer.

> Exception in thread search_thread-0:
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
>     self.run()
>   File "/usr/lib64/python2.7/threading.py", line 764, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/opt/pokemon/pogom/search.py", line 159, in search_thread
>     parse_map(response_dict, i, step, step_location)
>   File "/opt/pokemon/pogom/models.py", line 253, in parse_map
>     logPokemonDb(p)
>   File "/opt/pokemon/pogom/customLog.py", line 58, in logPokemonDb
>     cursor.execute(query, data)
> IntegrityError: duplicate key value violates unique constraint "encounter_id_unique"
> DETAIL:  Key (encounter_id)=(4843258148351874141) already exists.

**Comment by wjpvandenheuvel** [comment]
Nevermind, forgot to update the customlog.py file. (Stupid, I know).

**Comment by Brideau** [comment]
Glad you got it sorted!
