### ISSUE TITLE
Support local timezones

### ISSUE THREAD

**Issue by Brideau** [Brideau/pokelyzer#12]
Right now the time is in UTC. This is intentional as it simplifies things dramatically, but I'd like to have a properly timezone solution in the future.

Based on the Kimball approach, the proper solution to this is:

![screen shot 2016-07-29 at 11 01 56 am](https://cloud.githubusercontent.com/assets/844397/17250712/f2f8e1b0-557b-11e6-87ae-06695237031a.png)

We just need to implement this.

**Comment by proschu2** [comment]
I found a pretty useful formula which convert unix time in any time zone you need ( http://spreadsheetpage.com/index.php/tip/converting_unix_timestamps/ )

**Comment by Brideau** [comment]
This has been finished in the newest releast: https://github.com/Brideau/pokelyzer/wiki/Patches
