### ISSUE TITLE
Encounter_id is not actually unique 

### ISSUE THREAD

**Issue by Brideau** [Brideau/pokelyzer#17]
It turns out encounter_id is not completely unique: https://www.reddit.com/r/pokemongodev/comments/4vazmk/encounter_id_is_not_unique/

This should fix it, and I need to write a patch that does this:

```
ALTER TABLE public.spotted_pokemon
ADD CONSTRAINT unique_encounter_spawn
UNIQUE(encounter_id, spawnpoint_id);
```

**Comment by TheRealIceCracker** [comment]
How do I apply this fix?
(I'm completely database retarded and got here by following the setup guide)

**Comment by Brideau** [comment]
This ticket is actually a separate bug than the one you have. It looks like you need to update your customLog.py file with the newer one. Check the wiki page in the tab above or the sample file on the main page.

**Comment by TheRealIceCracker** [comment]
Yeah, weirdly enough I somehow had the era column already added to the table (from the July 30th patch), but not the bits of code to make use of it.  Anyway, thanks for the help!

**Comment by Brideau** [comment]
I am going to postpone anything that requires a python file change until my pull request with PokemonGo-Map (hopefully) goes through. It'll make these kinds of updates much easier.

**Comment by Brideau** [comment]
Fixed with https://github.com/Brideau/pokelyzer/commit/5c6f81e7e9aa176f6cbb6206c4d3693d06ca7905
