### ISSUE TITLE
pokemon_go_db_backup.tar corrupt?

### ISSUE THREAD

**Issue by Exi89** [Brideau/pokelyzer#19]
Hi,

trying to do a fresh install, but unable to open/extract the tar either on Windows or Ubuntu.

The only tar that works for me is the one from your original commit.

Thanks
J

**Comment by Brideau** [comment]
You shouldn't need to open the tar file to do the restore via pgAdmin - it expects it to be in tar format.

**Comment by Exi89** [comment]
Thanks for the swift reply, that does not work either, restore button greyed out in pgadmin. It is not greyed out with the original tar.

**Comment by Brideau** [comment]
Strange. Can you try the most recent version? I just did an update and I've manually verified it on a fresh database.

**Comment by Exi89** [comment]
No luck I am afraid, getting the following:

Process returned exit code 0.
C:/PostgreSQL/bin\pg_restore.exe --host localhost --port 5432 --username "postgres" --dbname "pokemon_go" --role "pokemon_go_role" --no-password  --list "C:\Users\J\Desktop\pokemon_go_db_backup.tar"
pg_restore: [archiver] input file does not appear to be a valid archive

**Comment by Exi89** [comment]
Not sure I actually have the newest file? On the repository it still shows the one from 42 minutes ago, with commit 54f4b77.

**Comment by Brideau** [comment]
Yes that's the version I'm using as well. I should really add the version number to them in the future to be explicit.

What version of Postgres and pgAdmin are you running?

**Comment by Exi89** [comment]
Strange just tried again, seems like this time it worked. Likely a weird error at my end, sorry to have you chasing this. Will let you know once I have everything up and running!

For now, many thanks!

**Comment by Brideau** [comment]
No trouble!
