### ISSUE TITLE
Installation Guide for Mac

### ISSUE THREAD

**Issue by ferazambuja** [Brideau/pokelyzer#20]
I've been trying to install on the Mac using the Ubuntu without any success.
Since most all the screenshots around here are from Mac I believe it's possible.

**Comment by Brideau** [comment]
I recommend just using the Postgres app for Mac, which comes with PostGIS: http://postgresapp.com/

It's what I use personally and it saves a lot of the configuration steps mentioned. I haven't had time yet to specify exactly which ones, but hopefully that gives you a good start.

**Comment by ferazambuja** [comment]
Yes, I'm still trying. The thing that I most the most is apt-get alternative.

**Comment by Brideau** [comment]
You actually shouldn't need to use any line that has that I don't think. The closest equivalent would be homebrew: http://brew.sh/

**Comment by ferazambuja** [comment]
I'm sorry, but this whole process is too painful for loading a simple table on tableau. I still don't get it why we need a sophisticated server database when the data volume doesn't ask for it. Is by far the most complicated script that I tried. I do appreciate all the effort; however, you guys should consider just fork pogomap and share the tableau table.

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/Users/fernandoazambuja/pogo/PokemonGo-Map-2.10/pogom/app.py", line 15, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation
  File "/Users/fernandoazambuja/pogo/PokemonGo-Map-2.10/pogom/models.py", line 16, in <module>
    from .customLog import printPokemon, logPokemonDb
  File "/Users/fernandoazambuja/pogo/PokemonGo-Map-2.10/pogom/customLog.py", line 4, in <module>
    import psycopg2
ImportError: No module named psycopg2

**Comment by Brideau** [comment]
It's not a simple table; that's why it's hard. It's an extensible, highly performant dimensional model with support for geospatial data types that allow it to work with any GIS software package or business intelligence tool on the market.

And just because your data doesn't volume doesn't require a server, does not mean everyone's doesn't. There are people running Pokelyzer with 20 simultaneous scanners for their city and require the features I've put into this. I'm building it for those people.

I am also actively build a connector to PokemonGo-Map that takes advantage of their webhooks. Stay tuned for that.

And please, before you open tickets, Google your error. You're missing the package that's named in the error above. Searching 'install psycopg2 os x' will solve your problem.

**Comment by BallTongue0** [comment]
Okay so after patching everything and changing the costomLog.py I got the same problem but i sorted the psycopg2 problem by installing it using pip install psycopg2 and you may have to point to the location of pg_config in the postgres.app content folder, but when that was done i got a new error and i can't solve this one by myself... 

Traceback (most recent call last):
  File "runserver.py", line 18, in <module>
    from pogom.app import Pogom
  File "/Users/USER/Documents/pokelyzer/PokemonGo-Map-develop/pogom/app.py", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation
  File "/Users/USER/Documents/pokelyzer/PokemonGo-Map-develop/pogom/models.py", line 19, in <module>
    from .customLog import printPokemon
  File "/Users/USER/Documents/pokelyzer/PokemonGo-Map-develop/pogom/customLog.py", line 16, in <module>
    conn = psycopg2.connect(dbname="pokemon_go", user="pokemon_go_role", password=args.pokel_pass, host="127.0.0.1")
AttributeError: 'Namespace' object has no attribute 'pokel_pass'

(EDIT) Just saw that this was closed, should i make a new issue? @Brideau

**Comment by Brideau** [comment]
@BallTongue0 Yes please!

**Comment by BallTongue0** [comment]
@Brideau I got it all sorted out when installing the requirements in a different way and changing back the customLog file to the old one. But now it seams that the API is not showing any pokemons so I'll have to wait to know if everything's working!

**Comment by Brideau** [comment]
Ah, yes, the data pipe is down for everyone at the moment. I'm hoping they get it sorted soon too.
