### ISSUE TITLE
adding pokemon_info table with existing datas

### ISSUE THREAD

**Issue by Unyxos** [Brideau/pokelyzer#21]
Hi,

I saw that there is a new table, pokemon_info, can I add this one without any risk to lose my datas collected since yesterday or is it better to delete everything and get a more clear database ?

**Comment by Brideau** [comment]
It shouldn't affect anything if you follow the directions outlined in the patch. You can pretty safely update any of the dimension tables (all of the tables except `spotted_pokemon`) without worrying about losing your data.
