### ISSUE TITLE
Wiki typo/duplicate line

### ISSUE THREAD

**Issue by mheguy** [Brideau/pokelyzer#22]
In https://github.com/Brideau/pokelyzer/wiki/Ubuntu-Setup-Instructions the line `If you go back into pgAdmin, right click the spotted_pokemon table and view the top 100 rows of data, you should see it being populated!` is repeated twice (the last line of the wiki entry and the 2nd-to-last line).

**Comment by Brideau** [comment]
Good catch! Just fixed it.
