### ISSUE TITLE
Only 4 tables not 5

### ISSUE THREAD

**Issue by ManiSingh** [Brideau/pokelyzer#23]
When I restore using the  pokemon_go_db_backup.tar file it only restores 4 tables and not 5. The "spotted_pokemon" table is missing.

Are you able to provide the SQL for me to run to add the table to the db?

**Comment by Brideau** [comment]
Make sure you have the PostGIS extension installed on your system. If not, the spotted_pokemon table will fail.

If you're running Windows, check the wiki for how to do that, as other people have had the same issue.

**Comment by ManiSingh** [comment]
But even in the guide it says i should see 5 tables and not 4. The issue here is the missing table i believe. PostGIS seems to be installed and i started the server again and it stops with this message (attached image)
![error](https://cloud.githubusercontent.com/assets/1318708/17277009/91c6f59c-5730-11e6-9796-d937b0987fea.PNG)

**Comment by Brideau** [comment]
I understand, but that table should be created during the Restore of the backup. In every case I've seen where it hasn't, it's because PostGIS was missing from the database. If you go to your database in pgAdmin, right click and go to New Object > New Extension, is postgis available in the dropdown for Name?

**Comment by ManiSingh** [comment]
Yeah I just checked and it is - you reckon it's worthwhile creating the DB again and restoring it?

**Comment by Brideau** [comment]
That's very strange. Yeah give it another try - sometimes these things sort themselves out.

**Comment by ManiSingh** [comment]
Seemed to appear now - very odd! Thanks for your help but now I have another issue. I'll try fixing it myself before asking for your help but i've attached it in case you've seen it before.
![error2](https://cloud.githubusercontent.com/assets/1318708/17277703/47840db0-5741-11e6-8ac1-d88e732434d0.PNG)

**Comment by Brideau** [comment]
Looks like you might not have the newest version of PokemonGo-Map, where they added in webhooks. Try doing a `git pull` on the directory again before modifying the files.

Or, if you want to make things really simple, check out my new post: http://www.whackdata.com/2016/07/31/pokelyzer-webhook-integration-pokemongo-map/
