### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by wjpvandenheuvel** [Brideau/pokelyzer#26]
Changed branch to version1-branch, applied latest sql patches installed and followed npm related instructions as explained in the readme.

> /opt/pokelyzer/app.js:64
>          query_string = `INSERT INTO spotted_pokemon
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> SyntaxError: Unexpected token ILLEGAL
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:935:3

Any ideas?

**Comment by Brideau** [comment]
Hmm, it might be having an issue with the ECMAScript 6 syntax there. What version of node are you running? (`node -v` if that helps)

**Comment by Brideau** [comment]
Do you happen to be running this in a virtual box? http://stackoverflow.com/questions/12719859/no-visible-cause-for-unexpected-token-illegal

**Comment by Brideau** [comment]
@freakjam Do a git pull and give it another try. I went back to the old string syntax to see if that helps.

**Comment by wjpvandenheuvel** [comment]
Apparently some old NodeJS version was still installed on my CentOS VM. (I had it installed to get Pokemongo-Map up & running).

`node -v
v0.10.42

Fixed everything with the following commands:
sudo yum remove nodejs (remove old version first)
curl --silent --location https://rpm.nodesource.com/setup_4.x | sudo bash - (install newest)

 ## Checking for existing installations...
- rpm -qa 'node|npm' | grep -v nodesource
  XNode.js v4.x LTS Argon == XNode.js v5.x

node -v
v6.3.1

updated npm related stuff:
sudo npm install npm -g

now working fine:
INFO: MainApp/14132 on daalder.maximum.local: Running server on port 9876`

**Comment by Brideau** [comment]
Excellent! Could you do a pull and see if it still works after I changed the quote syntax? Just want to be sure.

**Comment by wjpvandenheuvel** [comment]
Still works just fine after latest pull!

> Unpacking objects: 100% (23/23), done.
> From https://github.com/Brideau/pokelyzer
>    cb002b8..663ee6a  version1-branch -> origin/version1-branch
> Updating cb002b8..663ee6a
> 
>  INFO: MainApp/14315 on daalder.maximum.local: Running server on port 9876

Running both also works :)

**Pokemongo-Maps:**
2016-07-31 17:15:08,649 [search_thread-0][        models] [   INFO] Upserted 3 pokemon, 0 pokestops, and 0 gyms

**Pokelyzer:**
[2016-07-31T15:15:05.675Z]  INFO: MainApp/14396 on daalder.maximum.local: Pokemon with ID 16 found.
[2016-07-31T15:15:06.644Z]  INFO: MainApp/14396 on daalder.maximum.local: Pokemon with ID 21 found.
[2016-07-31T15:15:07.647Z]  INFO: MainApp/14396 on daalder.maximum.local: Pokemon with ID 19 found.

**Comment by Brideau** [comment]
Perfect! Thanks for testing that out!
