### ISSUE TITLE
Pokelyzer - being a noob

### ISSUE THREAD

**Issue by ManiSingh** [Brideau/pokelyzer#27]
Apologies for my ignorance but i'm on the last step which is;

> Run using:
> 
> DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='[YOUR PASS]' DB_PORT=5432 WS_PORT=9876 ERA=2  node app.js | bunyan -l info

I am failing to understand how to run this.. I open up CMD and run it through there but to no avail

**Comment by proschu2** [comment]
Open a terminal in the pokelyzer directory and simply copy it, put your password and press enter

**Comment by ManiSingh** [comment]
I tried that but it returns with DB_NAME is not recognised as an internal or external command etc..

I thought that was the way to do it too - I am using Windows if that helps.

**Comment by Brideau** [comment]
@ManiSingh Does this help? http://stackoverflow.com/a/28821955/937365

**Comment by xxsytriskxx** [comment]
I have the same issue, @Brideau added it to the Path and restarted but no luck.

**Comment by ManiSingh** [comment]
I added the variables and rebooted with no luck. the npm command runs fine but the one mentioned in my first post doesn't

**Comment by Brideau** [comment]
@xxsytriskxx @ManiSingh can you post a screenshot of the entire error message?

**Comment by xxsytriskxx** [comment]
![01](https://cloud.githubusercontent.com/assets/20542113/17279567/6736e1fe-5788-11e6-8940-5fc619c0354b.PNG)
![02](https://cloud.githubusercontent.com/assets/20542113/17279568/675dae9c-5788-11e6-9c72-0e919cd1604c.PNG)
The error and the way my directory is setup

**Comment by Brideau** [comment]
Can you try this:

```
set DB_NAME='pokemon_go'
set DB_USER='pokemon_go_role'
set DB_PASS='[YOUR PASS]'
set DB_PORT=5432
set WS_PORT=9876
set ERA=2
node app.js
```

It looks like Windows environment variables are set much differently

**Comment by xxsytriskxx** [comment]
I run those commands, or make a bat file, or? Sorry I don't come from a programming background @.@

**Comment by Brideau** [comment]
No worries! Jus try running them one at a time. If you copy and paste them into the terminal, it'll run each for you as well.

**Comment by xxsytriskxx** [comment]
![003](https://cloud.githubusercontent.com/assets/20542113/17279628/0b19e734-578a-11e6-9303-758ba65eaff2.PNG)

Do I have to type down? -> Set ERA=2

**Comment by Brideau** [comment]
Oops! My bad, I forgot to put `set` before ERA - I've updated the code above

**Comment by ManiSingh** [comment]
Seems like we're getting somewhere

It says authentication error even though it's 100% correct

![error](https://cloud.githubusercontent.com/assets/1318708/17279652/a7832112-5771-11e6-8fda-4d3d1279047a.PNG)

**Comment by Brideau** [comment]
Progress! What if you remove the quotes? Or use double quotes?

**Comment by xxsytriskxx** [comment]
@Brideau It worked! I just had to run the npm install then build grunt. Thanks for the help!

**Comment by Brideau** [comment]
Great, I'll go update the docs with the proper command.

**Comment by xxsytriskxx** [comment]
Whoops scratch that, I got the same errors as @ManiSingh

**Comment by ManiSingh** [comment]
And the saga continues!

![error](https://cloud.githubusercontent.com/assets/1318708/17279680/a1a3b850-5772-11e6-9e13-791e7a2569b1.PNG)

**Comment by Brideau** [comment]
Have you run the patch from the main Readme file? I believe it'll solve this.

**Comment by ManiSingh** [comment]
I just ran it now and it works!

Thanks so much for your help

**Comment by xxsytriskxx** [comment]
@Brideau I'm still getting the authentication error, I executed the patches already. Not sure what to do next :x

**Comment by ManiSingh** [comment]
Did you remove the speech marks? @xxsytriskxx

**Comment by xxsytriskxx** [comment]
@ManiSingh Still nothing

**Comment by xxsytriskxx** [comment]
Is there a specific way to run the patches? I might be doing it incorrectly.

**Comment by Brideau** [comment]
If it's the auth error you're getting the patch won't help with that. Can you post a screen shot of the commands you're running?

**Comment by xxsytriskxx** [comment]
![lslslsls](https://cloud.githubusercontent.com/assets/20542113/17279975/b9c04b84-5794-11e6-90e0-2e2626795f7e.PNG)

**Comment by Brideau** [comment]
OK, so just highlight your database in pgAdmin, click the SQL button in the top menu, and in the screen that opens, run this:

```
INSERT INTO _meta (db_version, last_update) VALUES ('v1.0-alpha', '2016-07-31');
ALTER TABLE spotted_pokemon DROP COLUMN name;
```

**Comment by xxsytriskxx** [comment]
"Query returned successfully with no result in 31 msec."

**Comment by Brideau** [comment]
K, now try running your program.

**Comment by xxsytriskxx** [comment]
My python runserver.py works fine. But its not feeding the data into my db. I must have screwed up somewhere. Gonna retry from scratch I guess

**Comment by Brideau** [comment]
Are you running both the webhook listner (app.js) and the python web app at the same time?

**Comment by xxsytriskxx** [comment]
EDIT: Sorry that error was a mistake. Yes I ran the first cmd with the commands you gave us earlier in the Pokelyzer folder. Still got the same errors as before. Kept it open and then ran the runserver.py command (which still worked normally with the exception of connecting to my db)

**Comment by xxsytriskxx** [comment]
It started working! I think I just had a typo in one of the commands. was rewriting it. Thanks for the help @Brideau :)

**Comment by Brideau** [comment]
Great to hear!
