### ISSUE TITLE
error: column "undefined" does not exist

### ISSUE THREAD

**Issue by Tuumi** [Brideau/pokelyzer#30]
So. I installed latest PokemonGo-Maps, and had it working.. Then I stumbled upon this pokelyzer and was already hooked..

Installed to ubuntu with all the things mentioned on the wikipage.. Got it running.. Fired up PokemonGo-Maps and it started finding pokemons just like it should.. Then checked back to Pokelyzer side and this is what I'm seeing:

[2016-07-31T23:34:07.978Z]  INFO: MainApp/876 on localhost: Pokemon with ID 13 found.
[2016-07-31T23:34:07.982Z] ERROR: MainApp/876 on localhost:
    Error running query { [error: column "undefined" does not exist]
      name: 'error',
      length: 103,
      severity: 'ERROR',
      code: '42703',
      detail: undefined,
      hint: undefined,
      position: '425',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '3090',
      routine: 'errorMissingColumn' }

Any idea how to fix this?-p

**Comment by Tuumi** [comment]
(Apparently I jumped the gun - git pull on PokemonMap seemed to fix the issues)

**Comment by Brideau** [comment]
Glad to hear it's sorted!
