### ISSUE TITLE
Grunt Build error?

### ISSUE THREAD

**Issue by Phant0mKnight** [Brideau/pokelyzer#31]
I'm not sure exactly how I got to this point, or how to fix it, but I was able to get the Pokemon Go map running, then tried to set Pokelyzer up and failing, then doing something wrong, deleting the old database to try and fix it, reinstalling exactly how the instructions say, getting up to starting the server up.
Anyone know what this means or how to fix it?

C:\Users***\Desktop\PokemonGo-Map-develop>python runserver.py -u (username) -p (password) -st 25 -k (Google API) -l (location)
2016-07-31 19:54:16,346 [    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.

**Comment by Brideau** [comment]
Try running `npm install` in the terminal, and then `grunt build` and that should do it.

**Comment by Phant0mKnight** [comment]
Server works again, just did "npm install."  Tried to do "grunt build," console accepted "grunt" as a command, but not "grunt build." However, I ran the "python runserver" command again, and everything's good. Thanks!
