### ISSUE TITLE
undefined error spam

### ISSUE THREAD

**Issue by powerpatch** [Brideau/pokelyzer#33]
I'm getting spammed these errors as soon as I launch the app.
I've tried running everything 100% fresh from the https://github.com/Brideau/pokelyzer/wiki/Windows-Setup-Instructions
as well as my customized server both throw these errors like crazy.

```
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":30,"msg":"Running server on port 9876","time":"2016-08-01T03:10:59.511Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":30,"msg":"Pokemon with ID 13 found.","time":"2016-08-01T03:11:24.003Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":30,"msg":"Pokemon with ID 58 found.","time":"2016-08-01T03:11:24.034Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":30,"msg":"Pokemon with ID 23 found.","time":"2016-08-01T03:11:24.054Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":50,"msg":"Error running query { [error: column \"undefined\" does not exist]\n  name: 'error',\n  length: 103,\n  severity: 'ERROR',\n  code: '42703',\n  detail: undefined,\n  hint: undefined,\n  position: '425',\n  internalPosition: undefined,\n  internalQuery: undefined,\n  where: undefined,\n  schema: undefined,\n  table: undefined,\n  column: undefined,\n  dataType: undefined,\n  constraint: undefined,\n  file: 'parse_relation.c',\n  line: '3090',\n  routine: 'errorMissingColumn' }","time":"2016-08-01T03:11:24.060Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":50,"msg":"Error running query { [error: column \"undefined\" does not exist]\n  name: 'error',\n  length: 103,\n  severity: 'ERROR',\n  code: '42703',\n  detail: undefined,\n  hint: undefined,\n  position: '425',\n  internalPosition: undefined,\n  internalQuery: undefined,\n  where: undefined,\n  schema: undefined,\n  table: undefined,\n  column: undefined,\n  dataType: undefined,\n  constraint: undefined,\n  file: 'parse_relation.c',\n  line: '3090',\n  routine: 'errorMissingColumn' }","time":"2016-08-01T03:11:24.100Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":50,"msg":"Error running query { [error: column \"undefined\" does not exist]\n  name: 'error',\n  length: 103,\n  severity: 'ERROR',\n  code: '42703',\n  detail: undefined,\n  hint: undefined,\n  position: '425',\n  internalPosition: undefined,\n  internalQuery: undefined,\n  where: undefined,\n  schema: undefined,\n  table: undefined,\n  column: undefined,\n  dataType: undefined,\n  constraint: undefined,\n  file: 'parse_relation.c',\n  line: '3090',\n  routine: 'errorMissingColumn' }","time":"2016-08-01T03:11:24.123Z","v":0}
{"name":"MainApp","hostname":"DESKTOP-JFKAKVD","pid":27372,"level":30,"msg":"Pokemon with ID 52 found.","time":"2016-08-01T03:11:24.295Z","v":0}
```

**Comment by Brideau** [comment]
Hi there,

Most of those aren't errors, but are info logs to let you know it is working correctly. For example "Pokemon with ID 13 found" lets you know its successfully finding Pokemon. If you'd like to suppress this, instead of the part in the command that says `bunyan -l info` use `bunyan -l warn`, which will only give you logs if there are warnings or errors.

There are errors, however, in the logs you show above. It looks like you need to apply the most recent patch listed in the Readme on the main page of the repo. Give that a try and those should go away.

**Comment by drasmuss** [comment]
I get the same error message (`Error running query { [error: column \"undefined\" does not exist]...`), and I have applied the patch. Before applying the patch it would say `[error: column \"name\" does not exist]`, now it says "undefined".

**Comment by Brideau** [comment]
@drasmuss: Have a look at this closed ticket - it should resolve that issue: https://github.com/Brideau/pokelyzer/issues/28

**Comment by drasmuss** [comment]
That did it, thanks!

**Comment by powerpatch** [comment]
Unfortunately It didn't do anything for me.
I've tried fresh installs and basic configurations of the latest develop and even a couple behind.
I followed the tutorial to the letter and even tried applying the patches.
It seems to say undefined no matter how I configure it

[2016-08-01T04:50:09.174Z] ERROR: MainApp/18936 on DESKTOP-JFKAKVD:
    Error running query { [error: column "undefined" does not exist]
      name: 'error',
      length: 103,
      severity: 'ERROR',
      code: '42703',
      detail: undefined,
      hint: undefined,
      position: '425',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '3090',
      routine: 'errorMissingColumn' }

It might also be worth mentioning the master branch has webhook support if that is the reason you are calling for it in the tutorial.

**Comment by powerpatch** [comment]
I found that the latest develop build has a broken one click setup.
Doing it manually has solved all my issues. (which is basically what the other thread said to do my bad)
Thanks for the help :+1:
