### ISSUE TITLE
spotted_pokemon table has no recorded pokemon

### ISSUE THREAD

**Issue by Phant0mKnight** [Brideau/pokelyzer#34]
Followed the Pokelyzer setup instructions, I have the PokemonGo-Map folder inside another folder called Pokelyzer. I extracted the Pokelyzer-master folder into the Pokelyzer folder. I performed "npm install" and "npm install -g bunyan".

C:\Users***\Desktop\Pokelyzer>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\***\Desktop\Pokelyzer\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users***\Desktop\Pokelyzer\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users***\Desktop\Pokelyzer\npm-debug.log
## C:\Users***\Desktop\Pokelyzer>npm install -g bunyan

> dtrace-provider@0.6.0 install C:\Users***\AppData\Roaming\npm\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

C:\Users***\AppData\Roaming\npm\bunyan -> C:\Users\**_\AppData\Roaming\npm\node_modules\bunyan\bin\bunyan
bunyan@1.8.1 C:\Users\_**\AppData\Roaming\npm\node_modules\bunyan
├── safe-json-stringify@1.0.3
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.5)
├── dtrace-provider@0.6.0 (nan@2.4.0)
└── moment@2.14.1

Then, I ran the server command with the wh parameter, and was able to view the map from localhost:5000, but was unable to read data on pgAdmin III or on Tableau.

**Comment by Brideau** [comment]
If I understand correctly you have a directory tree that looks like this, correct?
- C:
  - Users
    - Username
      - Desktop
        - Pokelyzer
          - PokemonGo-Map
          - Pokelyzer-master

If that's the case make sure to run the npm commands inside the Pokelyzer-master folder as that's where the package.json file is, which tells it everything it should install.

**Comment by Phant0mKnight** [comment]
Ok, I ran npm in the Pokelyzer-master folder, not sure if it worked.

C:\Users***\Desktop\Pokelyzer\pokelyzer-master>npm install

C:\Users***\Desktop\Pokelyzer\pokelyzer-master>npm install -g bunyan
/

> dtrace-provider@0.6.0 install C:\Users***\AppData\Roaming\npm\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

C:\Users***\AppData\Roaming\npm\bunyan -> C:\Users\**_\AppData\Roaming\npm\node_modules\bunyan\bin\bunyan
bunyan@1.8.1 C:\Users\_**\AppData\Roaming\npm\node_modules\bunyan
├── safe-json-stringify@1.0.3
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.5)
├── dtrace-provider@0.6.0 (nan@2.4.0)
└── moment@2.14.1

C:\Users***\Desktop\Pokelyzer\pokelyzer-master>node app.js | bunyan -l info
C:\Users\***\Desktop\Pokelyzer\pokelyzer-master\app.js:15
  port: process.env.DB_PORT || DB_PORT,
                               ^

ReferenceError: DB_PORT is not defined
    at Object.<anonymous> (C:\Users***\Desktop\Pokelyzer\pokelyzer-master\app.js:15:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

C:\Users***\Desktop\Pokelyzer\pokelyzer-master>

**Comment by Brideau** [comment]
Have you followed the updated (as of last night) Windows instructions? The command formatting was incorrect before, as Windows loads environment variables differently than other systems.

**Comment by Phant0mKnight** [comment]
Ok, deleted my old files, started instructions from scratch, successfully got pokemon go map to work. To make sure I do this right this time, could you explain what this step means?

Set the required environment variables by either typing these lines one at a time, putting them in the sample windowsBatch.bat file and dragging it into the Command Prompt and hitting enter.

**Comment by Brideau** [comment]
I'm a dummy - I left the lines of code out entirely. Sorry about that. Have a look at the wiki again.

**Comment by Brideau** [comment]
And just so you know exactly what's going on, the main thing you need to know here is what an environment variable is. Essentially there are 3 ways for you to pass in things like database names, usernames etc.:
1. Hard code them into the file (a bad idea because if you ever share your code with someone and forget to remove it, the password is right there)
2. Store them in a config file, which the software loads (a better idea because you can share your code and leave this file out)
3. When you open a terminal, store some variables temporarily in the terminal itself. Then, when you run a program from the same terminal, the program itself has access to them. These are called environment variables.

So what you're doing when you type `set DB_NAME=pokemon_go` is saying "set this environment variable DB_NAME equal to the value pokemon_go", and app.js knows to look for that environment variable and use it.

**Comment by Phant0mKnight** [comment]
Thanks for that, I felt like I was missing something. K, so now I did that, and I ran the Webhood listener, should I be getting these results?

C:\Users***\Desktop\Pokelyzer\pokelyzer-master>node app.js | bunyan -l info
C:\Users\***\Desktop\Pokelyzer\pokelyzer-master\app.js:15
  port: process.env.DB_PORT || DB_PORT,
                               ^

ReferenceError: DB_PORT is not defined
    at Object.<anonymous> (C:\Users***\Desktop\Pokelyzer\pokelyzer-master\app.js:15:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

C:\Users***\Desktop\Pokelyzer\pokelyzer-master>

**Comment by Brideau** [comment]
It looks like we both have bugs :)

Double check the spelling of your `set DB_PORT` line to make sure it's properly capitalized and exactly as it is in the docs.

The "|| DB_PORT" part should actually be "|| 5432", which provides a default port if none is specified, so that's a bug on my part. I'll make a change and push it.

**Comment by kilator** [comment]
I'm having similiar problem. I finally set up a MySQL database and told bunyan to use it using port 3306, but there is nothing being recorded into the database. My pokemongomap works well right now.

**Comment by Phant0mKnight** [comment]
Works great now, not sure if you want to update the wiki to show what to expect after running the command? Or to let people know that the app.js needs to be updated.

C:\Users\X\Desktop\Pokelyzer\pokelyzer-master>node app.js | bunyan -l info
[2016-08-01T17:55:22.407Z]  INFO: MainApp/22808 on X-PC: Running server on port 9876

**Comment by Phant0mKnight** [comment]
Ah. Just checked the database, still no recordings. Um, should I have 6 tables, 5 for pokemon, 1 for postgre?
![pgadmin pic](https://cloud.githubusercontent.com/assets/9942110/17303871/8a5586c8-57f0-11e6-87b8-11c8f0aeec31.png)

**Comment by Brideau** [comment]
@Phant0mKnight Those are the right tables, but that screen doesn't always display accurate information on the number of records. What do you get when you right-click the spotted_pokemon table and view the top 100 rows?

@kilator It sounds like you might be mixing up PokemonGo-Map and Pokelyzer. PokemonGo-Map has the option to store some data in MySQL, but Pokelyzer runs exclusively on Postgres.

**Comment by Phant0mKnight** [comment]
Got some blank rows here, not sure what's wrong.
![pokedata](https://cloud.githubusercontent.com/assets/9942110/17304058/9d6b512e-57f1-11e6-9843-bfc518456841.png)

**Comment by Brideau** [comment]
Can you send me a screenshot of the two terminals running Pokelyzer and PokemonGo-Map?

**Comment by kilator** [comment]
@Brideau Oh, i most likely am. So i cannot run pokelyzer on mysql? I have to keep running two separate databases, one for map and one for pokelyzer?

Thank you for your help, now and with the previous issue, and thanks for making this. :)

**Comment by Phant0mKnight** [comment]
Do you mean running the initial command without the -wh command and one with -wh?

**Comment by victordiec** [comment]
I'm having the same problem as Phant0mKnight and am running pokelyzer on windows.  Didn't have any configuration problems, just my spotted_pokemon table is empty
![image](https://cloud.githubusercontent.com/assets/12548773/17304172/43d350ac-57f2-11e6-85ce-c1466f2ea0c2.png)

**Comment by victordiec** [comment]
Does this have anything to do with Niantic removing the steps from pokemon?

**Comment by Brideau** [comment]
@kilator Yes that's the case. The default database that comes with most pokemon maps aren't designed for data analysis, so you end up bumping into yourself when you try to do anything beyond the specific case they were designed for. Pokelyzer is a database with a bit more beef to it.

@Phant0mKnight Like the ones that @victordiec just shared above.

**Comment by Brideau** [comment]
@victordiec Are any showing on your map? I sometimes see long strings of "Upserted 0 pokemon" for a while because the map just isn't finding any.

**Comment by victordiec** [comment]
I see the map, but I don't see any green circles.  They should be placed in the spotted pokemon table first right?

**Comment by kilator** [comment]
@victordiec as @Brideau said, you are not finding any pokemon. You should also change your accounts password since its visible in the commandline header. Also i'd recommend searching smaller area (step 25 is too much and will take ages). Step 5 is what everyone uses.

If you dont see any green circles, it means your map is not scanning the area, or the "Scanned Locations" is off in the map settings. Try writing your coordinates like -l 49.966837,16.971131 without the quotations and the space near the comma.

**Comment by victordiec** [comment]
haha thanks @kilator .  I'm using a throwaway anyways 
I'll reset the server with what you've said in mind.

**Comment by Brideau** [comment]
@victordiec I mean in the map that shows up if you go to localhost:5000

@kilator Is correct - if you use a grid that size, it basically finds takes forever to finish a loop and most of the scans won't have anything in them.

**Comment by Phant0mKnight** [comment]
K, I can see pokemon on my map, looks like the issue is password authentication for pokemon_go_role

![untitled](https://cloud.githubusercontent.com/assets/9942110/17304716/ec09be76-57f4-11e6-9f54-b6c780c80ecb.png)

![untitled2](https://cloud.githubusercontent.com/assets/9942110/17304766/38990f4e-57f5-11e6-8beb-1830488176f2.png)

**Comment by victordiec** [comment]
@Brideau This is what I see on localhost:5000
![image](https://cloud.githubusercontent.com/assets/12548773/17304795/5e7f6d02-57f5-11e6-9c87-a18449efd096.png)

Not sure if I did the Google Maps API key right.

**Comment by Phant0mKnight** [comment]
Don't really understand why this is the problem, there's no password, as far as I know.

**Comment by victordiec** [comment]
@Phant0mKnight Is the left console the result from running "node app.js | bunyan -l info"?

**Comment by Phant0mKnight** [comment]
Yes

**Comment by Phant0mKnight** [comment]
That's what I see while running the pokemongomap

**Comment by Brideau** [comment]
@Phant0mKnight When did you happen to go through the instructions to set up the database? The Windows guide was missing some pretty major steps until I fixed it late last night. Have a look again at the new instructions where it describes how to set a password for `pokemon_go_role`

**Comment by Brideau** [comment]
@victordiec Yeah that's a really common one. Check the settings in your Google API console and see if you've allowed connections from `*localhost*`. It sometimes takes a while for the change to stick as well.

**Comment by kilator** [comment]
@Phant0mKnight I've got the exact same problem earlier. My login information in variables in WindowsBatch.bat was wrong. Try checking your login info again if it matches that of your database. In my case i used pokemon_go as user instead of pokemon_go_role.

**Comment by Phant0mKnight** [comment]
Got it, fixed password issue. Now pokelyzer reads the pokemon seen, but no data is seen in pgAdmin or Tableau
![untitled3](https://cloud.githubusercontent.com/assets/9942110/17305158/2fc2d9e8-57f7-11e6-85e9-43b2c2daabfe.png)

**Comment by Brideau** [comment]
@Phant0mKnight Looks like you need to run the most recent patch in the repo Readme :)

**Comment by victordiec** [comment]
@Brideau 
Hey still getting this on my localhost:5000
![image](https://cloud.githubusercontent.com/assets/12548773/17306028/bd86e13a-57fb-11e6-8ae2-976bbab10fa2.png)

Is this what you meant by allowing connections to _localhost_
![image](https://cloud.githubusercontent.com/assets/12548773/17306054/ec733f7a-57fb-11e6-9c47-68ee9c299023.png)

**Comment by Brideau** [comment]
@victordiec Yep, sometimes it take hours before it takes effect though.

**Comment by victordiec** [comment]
@Brideau Ok Thanks!

**Comment by Phant0mKnight** [comment]
So, there are 4 patches in the pokelyzer folder, I'm guessing that I should use the pokemon_info_table_patch. There are 2 dat files, and a sql file in there, what do I do with them?

**Comment by khthe8th** [comment]
I have 25323 rows in my spotted pokemon table but now it stopped updating with new pokemon. I'm still upserting pokemon but nothing is being saved to my table. Seems to be a password issue but I have my password set correctly everywhere (I think) 

![image](https://cloud.githubusercontent.com/assets/5308389/17313656/5729ef60-5812-11e6-9137-d196e1abeaa9.png)

**Comment by Brideau** [comment]
@Phant0mKnight Actually all you should need is the most recent one mentioned here: https://github.com/Brideau/pokelyzer

```
INSERT INTO _meta (db_version, last_update) VALUES ('v1.0-alpha', '2016-07-31');
ALTER TABLE spotted_pokemon DROP COLUMN name;
```

**Comment by Brideau** [comment]
@khthe8th Make sure there are no quotes or anything in any of the user or password, and confirm that there is a password set on that user (double check the windows instructions around that - I updated it last night).

**Comment by Phant0mKnight** [comment]
How do I use that "pokemon_info_table_patch.tar" file?

**Comment by Brideau** [comment]
If you have a table called pokemon_info that has a bunch of data in it about all the pokemon, don't worry about it. The only patches you need to apply are the ones since you did the install.

If you do need it, you restore it the same way as the other tar file. It only updates part of the database and doesn't erase your data.

**Comment by Phant0mKnight** [comment]
Well, using the tar file did stop the Webhood listener from reporting errors, but I'm still not seeing any data on the spotted_pokemon table. How do I use the other patches?

**Comment by khthe8th** [comment]
@Brideau I've confirmed there is no quotes in any of the user or password when I run the windowsBatch.bat file. and that there is a password set on the login role in PostreSQL. Still get the error

**Comment by Brideau** [comment]
@khthe8th I've started a new ticket for you here: https://github.com/Brideau/pokelyzer/issues/44 The conversation here is getting a bit confusing since it's going in two directions :) 

@Phant0mKnight: All the patch instructions are in the Readme under Patches. And I'll need more information about what your terminals are currently showing to help you diagnose the problem - it's hard to do without much to go on.

**Comment by Phant0mKnight** [comment]
I've applied all the patches, and the info table patch returned "process returned exit code 1"

C:/Program Files/PostgreSQL/9.5/bin\pg_restore.exe --host localhost --port 5432 --username "postgres" --dbname "pokemon_go" --no-password  --verbose "C:\Users\JimFX\Desktop\Pokelyzer\pokelyzer-master\patches\pokemon_info_table_patch.tar"
pg_restore: connecting to database for restore
pg_restore: creating TABLE "public.pokemon_info"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 201; 1259 23728 TABLE pokemon_info pokemon_go_role
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "pokemon_info" already exists
    Command was: CREATE TABLE pokemon_info (
    pokemon_id bigint NOT NULL,
    name text,
    classification text,
    type_1 text,
    typ...
pg_restore: processing data for table "public.pokemon_info"
pg_restore: [archiver (db)] Error from TOC entry 3411; 0 23728 TABLE DATA pokemon_info pokemon_go_role
pg_restore: [archiver (db)] COPY failed for table "pokemon_info": ERROR:  duplicate key value violates unique constraint "pokemon_info_pkey"
DETAIL:  Key (pokemon_id)=(1) already exists.
CONTEXT:  COPY pokemon_info, line 1
pg_restore: creating CONSTRAINT "public.pokemon_info_pkey"
pg_restore: [archiver (db)] Error from TOC entry 3288; 2606 23735 CONSTRAINT pokemon_info_pkey pokemon_go_role
pg_restore: [archiver (db)] could not execute query: ERROR:  multiple primary keys for table "pokemon_info" are not allowed
    Command was: ALTER TABLE ONLY pokemon_info
    ADD CONSTRAINT pokemon_info_pkey PRIMARY KEY (pokemon_id);

pg_restore: creating INDEX "public.pokemon_info_pokemon_id_idx"
pg_restore: [archiver (db)] Error from TOC entry 3289; 1259 23736 INDEX pokemon_info_pokemon_id_idx pokemon_go_role
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "pokemon_info_pokemon_id_idx" already exists
    Command was: CREATE INDEX pokemon_info_pokemon_id_idx ON pokemon_info USING btree (pokemon_id);

pg_restore: setting owner and privileges for TABLE "public.pokemon_info"
pg_restore: setting owner and privileges for TABLE DATA "public.pokemon_info"
pg_restore: setting owner and privileges for CONSTRAINT "public.pokemon_info_pkey"
pg_restore: setting owner and privileges for INDEX "public.pokemon_info_pokemon_id_idx"
WARNING: errors ignored on restore: 4

Process returned exit code 1.

**Comment by Brideau** [comment]
@Phant0mKnight Please read the instructions in the Readme. It says to drop the table before applying the patch. If you don't follow the instructions, it won't work.

**Comment by Phant0mKnight** [comment]
Sorry for missing that bit of information, so I dropped the info table, and applied the patch. It works, got pokemon location data showing up on the tables.
![untitled4](https://cloud.githubusercontent.com/assets/9942110/17317329/78ba8616-584a-11e6-9429-948fa19a964f.png)
Small problem, wondering why names aren't showing up on the table.
![untitled5](https://cloud.githubusercontent.com/assets/9942110/17317346/a2522fa6-584a-11e6-9a83-3bc0b3b7b793.png)

**Comment by Brideau** [comment]
For that one, have a look at this thread: https://github.com/Brideau/pokelyzer/issues/42

**Comment by Phant0mKnight** [comment]
Thanks
