### ISSUE TITLE
new install instructions - pokemongo-map develop branch

### ISSUE THREAD

**Issue by hannahbanana** [Brideau/pokelyzer#35]
Hi there
I've tried to setup using the new install instructions for OSX, but it seems it isn't working with the develop branch at present - I'm getting the following error when I try to run the PokemonGo-Map server:
 [    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.

I realise this is an issue with PokemonGo maps, not pokelyzer, but the develop branch isn't always going to be ready to go - what do you suggest as a workaround?
Thanks!

**Comment by hannahbanana** [comment]
OK an update to this... I got grunt build sorted and the pokemongo map server is now working as expected with the WH stuff appended, but now I'm getting errors from pokelyzer & nothing is being added to the db:

[2016-08-01T05:02:14.894Z]  INFO: MainApp/1102 on Users-MacBook-Pro.local: Pokemon with ID 32 found.
[2016-08-01T05:02:14.896Z] ERROR: MainApp/1102 on Users-MacBook-Pro.local:
    Error running query { [error: null value in column "name" violates not-null constraint]
      name: 'error',
      length: 511,
      severity: 'ERROR',
      code: '23502',
      detail: 'Failing row contains (3244, null, NjM1NzYyNTA2NDE0MTk3ODk1Nw==, 1470027734666, 167674, 1469991902, 2016-08-01 05:05:02, 6ad65c3d8a9, 144.888121993779, -37.7497556344046, 32, 305, 20160801, 144.88826279346, -37.7501970523555, 0101000020E610000073C4D07E6B1C624038E11CFEF7DF42C0, 0101000020E6100000380518A66C1C624019B6FE7406E042C0, 2, v0.5, 2016-08-01 05:02:14.895069).',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'spotted_pokemon',
      column: 'name',
      dataType: undefined,
      constraint: undefined,
      file: 'execMain.c',
      line: '1699',
      routine: 'ExecConstraints' }

above error is repeating for every pokémon found...

**Comment by wjpvandenheuvel** [comment]
Did u apply the latest sql patches? The name column from the spotted_pokemon table was dropped. Check the patches section in the readme.

**Comment by hannahbanana** [comment]
EDIT: never mind, silly question on my part. Sorted, thank you!
