### ISSUE TITLE
Error when starting server.

### ISSUE THREAD

**Issue by BallTongue0** [Brideau/pokelyzer#36]
I run Postgress.app on mac and the Map is working perfectly on localhost but when i try to start pokelyzer from terminal i get this. Note that I'm not great with code but any help in the right direction is appreciated! 

Error running query { [error: column "undefined" does not exist]
      name: 'error',
      length: 103,
      severity: 'ERROR',
      code: '42703',
      detail: undefined,
      hint: undefined,
      position: '425',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '3090',
      routine: 'errorMissingColumn' }

**Comment by BallTongue0** [comment]
When not having the map going i don't get any error but it won't give me a new prompt after writing 

DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='[YOUR PASS]' DB_PORT=5432 WS_PORT=9876 ERA=2  node app.js | bunyan -l info 

But as soon as i start the map i get the error mentioned above.

**Comment by Brideau** [comment]
Hi there, have a look at this previous ticket - it should clear things up: https://github.com/Brideau/pokelyzer/issues/28

**Comment by BallTongue0** [comment]
Thanks, got it working now!
