### ISSUE TITLE
Cannot use Webhook with multiple workers

### ISSUE THREAD

**Issue by kilator** [Brideau/pokelyzer#37]
Every time i run pokelyzer with multiple workers using webhook, i get an error saying the database is locked. I am pretty sure this is because the database only accepts one connection at a time. Is there any way to fix it so that i can collect data again?

**Comment by Brideau** [comment]
That's an issue with PokemonGo-Maps SQLite database and not the Pokelyzer one. Have a look over in their issues section to as I think this has come up a few times: https://github.com/AHAAAAAAA/PokemonGo-Map/issues
