### ISSUE TITLE
'bunyan' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Apathialol** [Brideau/pokelyzer#38]
Everything else went smoothly but I can't seem to get past this point.

![untitled](https://cloud.githubusercontent.com/assets/8907839/17302266/61c39e5e-57e9-11e6-9573-1c2f9a8987fd.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/8907839/17302315/a079d1d6-57e9-11e6-8fa1-13cbb55c9085.jpg)

**Comment by Brideau** [comment]
If you're already ran both `npm` commands, try restarting your terminal. The terminal itself has to load bunyan after install so it can run a special component of it.

**Comment by Apathialol** [comment]
I tried to restart my computer but I still get the same error.

![untitled](https://cloud.githubusercontent.com/assets/8907839/17304227/93b5f99e-57f2-11e6-8d59-a3ae94319573.jpg)

**Comment by Brideau** [comment]
And you've run both `npm install` and `npm install -g bunyan`?

Worst case scenario, you could just run `node app.js`, as bunyan just makes the logs prettier

**Comment by spac3w1zard** [comment]
I had this issue, too. I ended up finding a workaround when I had another issue with a different npm package. `npm install -g bunyan` doesn't seem to be updating the path environment variable.

I added `%USERPROFILE%\AppData\Roaming\npm` to my path environment variable, and that fixed the problem. Hope this helps!

Edited to add: After you've updated the variable, you will need to close out of the current cmd windows and open new ones.

Here's a tutorial for updating the path environment variable:
http://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7

**Comment by Brideau** [comment]
Awesome! Do you know if that path is consistent across Windows versions and npm installs?

**Comment by spac3w1zard** [comment]
I'm not very familiar with npm, but based on [this guide](http://tstringer.github.io/npmjs/javascript/nodejs/2016/02/26/npm-global-packages.html), using the command `npm root -g` will give you the path for global modules. If the command returns `C:\Users\<username>\AppData\Roaming\npm\node_modules`, then adding `%USERPROFILE%\AppData\Roaming\npm` to the path variable should work, as the .cmd files for modules will be in the npm directory (vs the npm\node_modules directory).

**Comment by Brideau** [comment]
I simply got rid of Bunyan because it was causing way more problems than it was helping fix, so this problem should now be fixed.

**Comment by donmilorad87** [comment]
Use "| bunyan" without flags...

**Comment by kishanp27** [comment]
Thanks boss
