### ISSUE TITLE
Column Undefined

### ISSUE THREAD

**Issue by claimer21** [Brideau/pokelyzer#41]
Getting the same column undefined error as in #28 and #29.

I've repulled from git develop branch not using easy setup and still having the issue.

**Comment by Brideau** [comment]
In the models.py file, can you post the code for the `webhook_data` object? It should be around line 267.

**Comment by claimer21** [comment]
webhook_data = {
                    'encounter_id': b64encode(str(p['encounter_id'])),
                    'spawnpoint_id': p['spawnpoint_id'],
                    'pokemon_id': p['pokemon_data']['pokemon_id'],
                    'latitude': p['latitude'],
                    'longitude': p['longitude'],
                    'disappear_time': calendar.timegm(d_t.timetuple())
                }

```
            send_to_webhook('pokemon', webhook_data)
```

**Comment by Brideau** [comment]
And you're sure you pulled from the newest develop branch, because it has the two extra fields I added in that aren't in your function:
https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/models.py#L267

Did you get an error when you did the git pull, or did you download the zip file and replace the folder?

**Comment by claimer21** [comment]
I replaced the folder, however I've just done a fresh install of dev usiing git pull.  Will report back in a bit.

**Comment by claimer21** [comment]
Got it setup, patched successfully, webhook server is running, but now my map is giving me this error:

http://imgur.com/a/hbGjU

**Comment by Brideau** [comment]
It looks like some relics are left over from the original setup. I would rename the PokemonGo-Map folder something entirely different and do a fresh install. No data will be lost in the process.

**Comment by claimer21** [comment]
It is a fresh install and it's named something different

**Comment by Brideau** [comment]
I'm baffled then...the line that is throwing that error simply doesn't exist in the develop branch of PokemonGo-Map, so I don't know how it could be causing the error...

**Comment by Brideau** [comment]
@moggd Any luck?

**Comment by Brideau** [comment]
Closing since there's been many updates since this was opened. Please reopen a new ticket if this issue continues to exist.
