### ISSUE TITLE
spotted_pokemon table missing name character varying

### ISSUE THREAD

**Issue by asadaizaz** [Brideau/pokelyzer#42]
![image](https://cloud.githubusercontent.com/assets/20784816/17315069/b6efa9d4-581d-11e6-9f87-959a74a7fddb.png)

It seems to be missing for me

**Comment by Brideau** [comment]
It was intentionally dropped when the switch was made to v1.0-alpha. It's best practice is dimensional modeling to use an id in the main table (spotted_pokmon) to reference a table that has much more detail about that "thing". 

In this case, the pokemon_info table has a matching id to the pokemon_id column in spotted_pokemon, and pokemon_info includes more detail about each pokemon. In Tableau/PowerBI, you can do a join on these two tables and it merges them together for you in a very efficient way.

**Comment by Brideau** [comment]
If you're getting an error from the wehhook listener, just apply the patch mentioned in the main readme in this repo.

**Comment by asadaizaz** [comment]
Ahh I see, so tableau will display them. Thank you

**Comment by asadaizaz** [comment]
Accidentally closed the issue, sorry about that.

Anyway, can you give me some basic instructions in how I would go about achieving that.

**Comment by Brideau** [comment]
@asadaizaz Sure, I've updated the instructions over here to reflect the new tables: https://github.com/Brideau/pokelyzer/wiki/Mapping-with-Tableau

**Comment by xxsytriskxx** [comment]
@Brideau When I drag Name into Pages. All I get is "Null". How do I get it back to showing the names of each pokemon again? 
![tttt](https://cloud.githubusercontent.com/assets/20542113/17347340/60397080-5920-11e6-9884-a5c04000085c.PNG)
