### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by Zephyr-Rising** [Brideau/pokelyzer#43]
Whenever I use npm install to fix the grunt build issue, it doesn't work.  I've tried everything I can, but to no avail.  Here is the error message I get:

![grunt build](https://cloud.githubusercontent.com/assets/4510586/17315478/aac9ea0e-5820-11e6-82a7-b78de43e5493.JPG)

Thanks for any help that you can give me.

**Comment by Brideau** [comment]
The develop branch isn't always stable, so it's possible it's an error with a recent addition to it.

Try this version: https://github.com/AHAAAAAAA/PokemonGo-Map/archive/7465e024433e75589ca85216779a0c862bf14b40.zip

If that doesn't work, I'd post an issue in their github repo, as I'm not overly familiar with their code: https://github.com/AHAAAAAAA/PokemonGo-Map/

**Comment by spac3w1zard** [comment]
I had a similar issue when I was installing pokelyzer last night. The way I fixed it was to delete the node_modules folder in the PokemonGo-Map-develop directory, then run `npm install` and `grunt build` again.

**Comment by Brideau** [comment]
@Zephyr-Rising Any update on this?

**Comment by Zephyr-Rising** [comment]
@Brideau It was working great before, and your fix worked.  However, I can't find any Pokemon anymore.  Is this because of the API changes?

**Comment by Brideau** [comment]
Yeah, everything is down at the moment.
