### ISSUE TITLE
Authentication Issue With Postgres

### ISSUE THREAD

**Issue by Brideau** [Brideau/pokelyzer#44]
Moving your thread here to keep the other ticket clean. Here's the original screenshot you posted:
![](https://cloud.githubusercontent.com/assets/5308389/17313656/5729ef60-5812-11e6-9137-d196e1abeaa9.png)

Try resetting the password by going to the Login Roles part of the tree menu, right clicking your user and setting it in the definitions tab. This seemed to solve it for other people.

<img width="260" alt="screen shot 2016-08-01 at 11 56 40 pm" src="https://cloud.githubusercontent.com/assets/844397/17315640/b5880a02-5843-11e6-8f61-2aea4e0b3437.png">

**Comment by khthe8th** [comment]
I have done that about 6 times and it doesn't seem to work. I am setting it to the same password I have in WindowsBatch.bat. Is there anywhere else the password needs to be set that I'm missing?

**Comment by Brideau** [comment]
OK, so we can rule that part out. 

What version of Windows are you running?

**Comment by Brideau** [comment]
What happens if you try this method for setting environment variables: http://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7

**Comment by khthe8th** [comment]
Windows 7. I've also deleted the role and recreated it with the same password. I also closed and reopened pgadmin. My table won't add any more rows after 25323. I'm using the latest master build of pokemon go map.

**Comment by Brideau** [comment]
You'll need to use the latest develop build of PokemonGo-Map or else you'll get another error after this one is sorted.

**Comment by khthe8th** [comment]
Yea I tried that but was getting errors when I tried to run grunt build so went back to master

**Comment by Brideau** [comment]
Try this version - it's the one just after the pull request I made to them: https://github.com/AHAAAAAAA/PokemonGo-Map/archive/7465e024433e75589ca85216779a0c862bf14b40.zip

**Comment by Brideau** [comment]
I'm going to create another branch of pokelyzer in a moment that has a compatibility library for windows in it and send you the link. I appreciate your patience with this.

**Comment by khthe8th** [comment]
I get the below image when I try to run npm install on a dev build

![image](https://cloud.githubusercontent.com/assets/5308389/17316822/1095d14e-582c-11e6-9442-e0cc9fb452f3.png)

**Comment by Brideau** [comment]
@khthe8th Scratch what I just said, it's just introducing more complexity. Can you post the batch file you're running?

Try restarting your terminal following running `npm install -g bunyan`

**Comment by khthe8th** [comment]
which batch file? Your windowsbatch.bat?

set DB_NAME=pokemon_go
set DB_USER=pokemon_go_role
set DB_PASS=******
set DB_PORT=5432
set WS_PORT=9876
set ERA=2

where *****\* is the same password I am inputting in the definition tab of pokemon_go_role in pgAdmin III

**Comment by Brideau** [comment]
That looks good to me. I know this sounds overly simple, but I want to explore every option: have you tried typing those lines in one at a time before running the app? I've only tested this on Windows 10 so I don't know the subtle differences between command prompts in the different versions.

**Comment by khthe8th** [comment]
yes I tried that as well

**Comment by khthe8th** [comment]
I'm running node app.js instead of node app.js | bunyan -l info since it says bunyan is not an internal or external recognized command

**Comment by Brideau** [comment]
Let's try the next-most-hacky approach: hard code them into app.js just to see if it works. Just replace each part in the config variable so it looks like this:

```
var config = {
  user: 'pokemon_go_role',
  database: 'pokemon_go',
  password:'****',
  port: 5432,
  max: 20,
  idleTimeoutMillis: 30000
}
```

Yeah bunyan is optional - it just makes the logs easier to read.

**Comment by khthe8th** [comment]
hey that fixed that part of it! Now something else is messed up though. Seems I am missing some columns. Maybe on too old of a pokemap build?

![image](https://cloud.githubusercontent.com/assets/5308389/17317064/991a7ca2-582e-11e6-8550-e4e59abb9a6e.png)

**Comment by Brideau** [comment]
Ahh, I know this one! That's caused by using a build from before my pull request. You'll need one from this time on: https://github.com/AHAAAAAAA/PokemonGo-Map/tree/7465e024433e75589ca85216779a0c862bf14b40

**Comment by Brideau** [comment]
And it sounds like I'll need to build an alternative way of inputting the config for windows machines. This is a mess...

**Comment by khthe8th** [comment]
well so back to yours then. Any idea why I get the below error

![image](https://cloud.githubusercontent.com/assets/5308389/17317133/4d4647ba-582f-11e6-8a6d-1f26b94fbeff.png)

**Comment by Brideau** [comment]
How old is your npm and node installation? Have you run `npm update -g` in a while?

**Comment by khthe8th** [comment]
I just installed npm and node in the past couple days when I started playing around with all of this. I just ran npm update -g and then tried npm install again and got the same errors

**Comment by Brideau** [comment]
Wait a second, it looks like you're running that in the PokemonGo-Map directory. All these commands you've been running, have you been running them in the pokelyzer directory or the pokemongo-map one?

**Comment by khthe8th** [comment]
hmm this one in map directory, node app.js and batch file in pokelyzer

**Comment by khthe8th** [comment]
I'm following this https://jonaharagon.github.io/PoGoMapWiki/#!Windows-Installation-and-requirements.md right now trying to get the grunt build of the map installed and working

and I'm failing on this part
Develop branch only instructions
In order for the map to load on the develop branch, there are some additions requirements.

Install node.js. That will install the npm command.
-[Node.js 6.3.1](https://nodejs.org/dist/v6.3.1/node-v6.3.1-x64.msi)
Open an admin command prompt and type npm install -g grunt-cli . This installs Grunt's command line interface (CLI) globally.
Once grunt is installed, run it by typing npm install. This will automatically run the grunt build command.

**Comment by Brideau** [comment]
It's possible the dev branch is currently broken, as it was for somebody else today. I'd tring a few different versions and if you're still having trouble open a ticket over in their repo.

**Comment by khthe8th** [comment]
Hmm yea I tried the branch you linked above and the most recent Dev branch and they both fail in that same npm install spot. I also noticed that they both throw an error while running easy setup but it still let's me continue, enter my api key, and finish the easy setup

**Comment by khthe8th** [comment]
I guess for now I will just scan and not log to my database

**Comment by GareRam** [comment]
I'm having the exact same login issue. Also with hardcoding it into app.js. 

[2016-08-02T07:50:05.107Z] ERROR: MainApp/12056 on koala:
    Error fetching client from pool { [error: password authentication failed for user "pokemon_go_role"]
      name: 'error',
      length: 104,
      severity: 'FATAL',
      code: '28P01',
      detail: undefined,
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'auth.c',
      line: '285',
      routine: 'auth_failed' }

I am 100% sure my pass is correct :(

**Comment by GareRam** [comment]
I have no idea why, but I ran through the whole windows process, and now it's filling the DB.

**Comment by Brideau** [comment]
@Gareram nice to head its working. What do you mean when you say you ran through the whole windows process?

**Comment by GareRam** [comment]
@Brideau basically re-installing postgre, and setting up all over again, apart from the pogo-map.

The only issue at this moment I have is I cannot find pokemon by name, but by number, but that's a small flaw :)

Love the project thus far! I am gathering as much information as possible about nests in my region. Even if Niantic decides to pull the plug on all fan-projects in some way, I can set up a page for my city and point people where they need to go. Thumbs up!

**Comment by Brideau** [comment]
Ah, very strange! For the name thing, see this: https://github.com/Brideau/pokelyzer/issues/42

And thank you!

**Comment by ghost** [comment]
I also had the same issue just because not reading carefully. I forgot to do this before running the "app.js"

```
set DB_NAME=pokemon_go
set DB_USER=pokemon_go_role
set DB_PASS=[Your Pass]
set DB_PORT=5432
set WS_PORT=9876
set ERA=2
```

Then it worked after typing this:

`node app.js | bunyan -l info`

---

I created a startcript to run pokelyzer.

Try this:
1. Create a new File 
2. Add this to ur file: 

```
cd "C:\Users\USER\Downloads\PokemonGo-Map-develop\pokelyzer-master"   #Change this Path to YOUR pokelyzer Folder
set DB_NAME=pokemon_go
set DB_USER=pokemon_go_role
set DB_PASS=[Your Pass]
set DB_PORT=5432
set WS_PORT=9876
set ERA=2
node app.js | bunyan -l info
pause
```

3.Save file as "*.bat"
4.Run it

**Comment by WilliamW1979** [comment]
I have your fix!

python runserver.py -a ptc -u [USER NAME] -p [POKEMON TRAINER PASSWORD] -l "[LOCATION]" -st 25 -H 127.0.0.1 -k [GOOGLE MAPS ID] -wh http://localhost:9876 --db-user pokemon-go-role --db-name pokemon_go --db-pass [DATABASE PASSWORD]

This bypasses the need for using local variables which is the problem! You are entering the password in the command line instead!

**Comment by Brideau** [comment]
@WilliamW1979 That looks like it works for the PokemonGo-Map python app, but I don't think it works with the Pokelyzer Node app :(

**Comment by spac3w1zard** [comment]
@khthe8th I had the same problems when I was installing pokelyzer last night. Here's what worked for me:

1) Add `%USERPROFILE%\AppData\Roaming\npm` to the path environment variable. I did this because bunyan and grunt were both giving me 'is not recognized as an internal or external command' errors. **If you aren't getting these errors, then you don't need to do this step.** After you've updated the variable, you will need to close out of the current cmd windows and open new ones.
2) Delete the node_modules folder in the PokemonGo-Map-develop directory, then run `npm install` and `grunt build` again.
3) Rerun your windowsbatch.bat file.

If that doesn't work, please let me know. I was able to get everything up and running the way it's supposed to be on my laptop, but I stupidly didn't write down the exact steps. If the above doesn't work for you, I'll try to install it from scratch on a different Windows computer later tonight, and take detailed notes about the changes needed to get it working properly.

**Comment by Brideau** [comment]
@khthe8th How's this coming?

**Comment by khthe8th** [comment]
I added the environment variable and deleted the node modules folder but when I run npm install I still get the same errors as my last screenshot above. I think I've given up on it for now. I read the scan timer increased to 10seconds anyways from 5

**Comment by Brideau** [comment]
Sorry to hear that, I'll close this ticket for now then but let me know if you decide to give it another shot in the future.
