### ISSUE TITLE
Final Schema

### ISSUE THREAD

**Issue by viperfx** [Brideau/pokelyzer#46]
Hi, 

Ive noticed there are a bunch of patches. It would be great if you can add a basic Schema drawing or dump of the final schema after the patches.

is pokelyze_sql.sql the final schema?

Thanks

**Comment by Brideau** [comment]
Good idea. Here's what it looks like - I'll add it to the readme as well:

<img width="1062" alt="screen shot 2016-08-02 at 12 05 15 am" src="https://cloud.githubusercontent.com/assets/844397/17329922/1f6d9764-589b-11e6-9b89-13cf365cb53c.png">

pokelyze_sql.sql is _almost_ the final schema, as the date and time dimensions have to be created in a Python script. The code to do that is here: https://github.com/Brideau/pokelyzer/blob/master/DateTimeDimensionGenerator.ipynb

**Comment by viperfx** [comment]
Awesome! I think other thing that would be useful is an API spec for your node app. We are posting to an endpoint, the encounters. It would be great if you could add a sample JSON too of the payload.

**Comment by Brideau** [comment]
Also a good idea! I'll take that on when I do the integration with pokeminer.

**Comment by viperfx** [comment]
Great! For now, would you be able to paste a sample of the JSON payload that the node app is receiving, when you get a chance. That would help me a lot!

**Comment by Brideau** [comment]
Just added it to the main readme here: https://github.com/Brideau/pokelyzer/blob/master/README.md

**Comment by viperfx** [comment]
❤️

**Comment by viperfx** [comment]
I have a quick question, since the recently discovery of encounterId not being so unique. 

On app.js, don't you need to check for both? Right now its check just encounter_id. 

```
ON CONFLICT (encounter_id)
```

**Comment by Brideau** [comment]
My understanding was that that was only a problem with a few data points during the spawn point swap. Have you read somewhere that it's a wider problem?

**Comment by viperfx** [comment]
Just from here: 

https://www.reddit.com/r/pokemongodev/comments/4vazmk/encounter_id_is_not_unique/

**Comment by viperfx** [comment]
Back on to the topic of schemas, 

how is pokemon_go_db_backup.tar and pokelyze_sql.sql related? From a fresh install, the wiki suggests using the tar file. In which situation is what file supposed to be used?

**Comment by Brideau** [comment]
I think my brain just went a bit wonky. I had totally forgot that I already wrote a bug for this and planned to fix it: https://github.com/Brideau/pokelyzer/issues/17

pokelyze_sql.sql is hand-written sql for creating all the tables except the date and time dimensions, which have to be created with a script. Once I've run that SQL and generated the date/time ones, I get a properly configured, empty database. I then make a backup from that so that nobody needs to go through the same process because I haven't automated it yet.
