### ISSUE TITLE
Suggestion: Add support for rarity 

### ISSUE THREAD

**Issue by jlarrigan** [Brideau/pokelyzer#48]
It would be wonderful to be able to filter based on rarity. 

Thanks, keep up the good work.

**Comment by Brideau** [comment]
I've been thinking about that too, but couldn't find consistent info. Do you know of a good data source?

**Comment by Brideau** [comment]
@jlarrigan Done! See the Readme on the homepage for patching instructions.

**Comment by Brideau** [comment]
Closed with: https://github.com/Brideau/pokelyzer/commit/30d0aa19b70367eae87250268f6239895903631b

**Comment by jlarrigan** [comment]
Killer!, thanks @Brideau
