### ISSUE TITLE
python error while running map after installed Pokelyzer

### ISSUE THREAD

**Issue by Unyxos** [Brideau/pokelyzer#5]
Hi,

After installing Pokelyzer i have this error when I want to launch the map :

`Traceback (most recent call last):
  File "runserver.py", line 16, in <module>
    from pogom.models import init_database, create_tables, Pokemon, Pokestop, Gym
ImportError: cannot import name init_database`

And I can't find how to fix it by myself

**Comment by Brideau** [comment]
Can you post your models.py file? It looks like it's trying to find a function called init_database() but can't find it there.

**Comment by Unyxos** [comment]
Hi,

Here is the models.py file : 

http://pastebin.com/LpG1WVHT

I took the sample_models.py file

**Comment by Brideau** [comment]
Ah, that explains it. They changed that file today and added that new function. I just updated the sample_models.py file, so the new one should be safe to use. Let me know if that works.

**Comment by Unyxos** [comment]
alright, it's fixed, just a last issue : 
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 7: ordinal not in range(128)

**Comment by Brideau** [comment]
Is that the whole error? Any indication of which file it's in?

**Comment by Unyxos** [comment]
I fixed it by switching the database to UTF-8 encoding instead of ASCII

**Comment by Brideau** [comment]
Glad to hear you got it!
