### ISSUE TITLE
Is it possible to move old spotted_pokemon Data to the new DB?

### ISSUE THREAD

**Issue by ghost** [Brideau/pokelyzer#50]
I have an old DB with 3k spotted Pokemon entries.
Today I updated my Pokelyzer with the new DB.
I saw that there are new Columns in the new spotted_pokemon table.
I tought i can add the columns 'pokemon_go_era,meta_db_version, meta_row_insertion_time' fill them with correct data and remove the name column to have an exact table like the new version so i just copy paste aall the data (Not forgot to change the ID of every spotted Pokemon).
But i saw that the "encounter_id" also changed how it generates the characters

before:
![image](https://cloud.githubusercontent.com/assets/13746733/17332122/f1ccbf96-58cd-11e6-98c9-fee6a3ade76d.png)

after: 
![image](https://cloud.githubusercontent.com/assets/13746733/17332102/e053b0e4-58cd-11e6-83ac-66fddd353029.png)

Are the old encounter_id's compatible with the new DB?

**Comment by Brideau** [comment]
Huh, I hadn't actually noticed the change in the encounter_id format. They must have changed it for some reason. We just passively receive that data and store it, and as long as it's unique, it should be fine! Migrate away!

**Comment by Brideau** [comment]
Ah, I just spotted where the change comes from. The webhook that PokemonGo-Map provides encodes the encounter id, and I didn't decode it. I'll have to fix that, but it should't be a big problem for historical data since the codes would still be unique and their main purpose is deduping.

**Comment by ghost** [comment]
Yeah it worked :+1: 
Thanks

**Comment by Brideau** [comment]
Officially fixed in with this commit: https://github.com/Brideau/pokelyzer/commit/5a7b889e56a5b9322bc7a91c1cef30ab54a3ca61

**Comment by ghost** [comment]
Great :)

I found something new. 
I ran Pokelyzer today. Because i manually entered the rows and manipulated the IDs i get this error:

```
[2016-08-03T09:25:09.182Z]  INFO: MainApp/7080 on GGSAIJs: Running server on port 9876
[2016-08-03T09:25:24.325Z]  INFO: MainApp/7080 on GGSAIJs: Pokemon with ID 96 found.
[2016-08-03T09:25:24.341Z] ERROR: MainApp/7080 on GGSAIJs:
    Error running query { [error: duplicate key value violates unique constraint "id_primary_key"]
      name: 'error',
      length: 194,
      severity: 'ERROR',
      code: '23505',
      detail: 'Key (id)=(2632) already exists.',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'spotted_pokemon',
      column: undefined,
      dataType: undefined,
      constraint: 'id_primary_key',
      file: 'nbtinsert.c',
      line: '424',
      routine: '_bt_check_unique' }
```

In this case it wants to give the new spotted pokemon the ID 2632.
On my DB Im now on ID 10532.

How can I tell Pokelyzer that he should use ID 10533 for new Mons?

**Comment by Brideau** [comment]
The IDs should auto-generate since they are of type serial, so you shouldn't need to pass that value in when you do the insert. 

If you can, an easy way to import the data would be to iterate through all the rows in your current db, and send in only the fields shown here: https://github.com/Brideau/pokelyzer#the-webhook-listener

That way all the generated fields (there are quite a few) will auto-create for you.

**Comment by Brideau** [comment]
@SimplyArmin I found a proper solution to this, which resets the serial count value:

```
SELECT pg_catalog.setval(pg_get_serial_sequence('spotted_pokemon', 'id'), (SELECT MAX(id) FROM spotted_pokemon)+1);
```

If that doesn't solve the problem, let me know.
