### ISSUE TITLE
No data being parsed to pokelyzer.

### ISSUE THREAD

**Issue by Rechinan** [Brideau/pokelyzer#51]
After much faffing around i finally have pogomap up and running with the pokelyzer but nothing is being sent to the database at all. Chances are I have missed something so obvious but I'd appreciate any help someone could give me?

To clarify I have the database set up and functioning along with the dev branch map server and WH.

I had this working using the master pogomap branch but got undefined column errors, after starting fresh and getting pogomap updated nada is received in the cmd prompt window.

![ss 2016-08-02 at 09 35 18](https://cloud.githubusercontent.com/assets/5929458/17344174/247a59be-58f9-11e6-97a0-a83fd488e100.png)

**Comment by spac3w1zard** [comment]
What args are you using for your `python runserver.py` command? (Remove your username, password, and api key data if/when you post it!) Make sure you have included the `-wh http://localhost:9876` argument.

**Comment by Rechinan** [comment]
Im using the config file to avoid having to type in a novel for an argument every time I launch, here is said config though and thanks for the reply

```
# Authentication settings
#auth-service:          # ptc (default) or google <<using ptc fyi so no change
username: -removed
password: -removed

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
location: 55.929260, -3.283973
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#scan-delay:            # default 5
step-limit: 25          # default 12

# Misc
gmaps-key: -removed            # your Google Maps API key
#webhook: http://localhost:9876              # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

#Uncomment a line when you want to change its default value (Remove # at the beginning)
#username, password, location and gmaps-key are required

```

**Comment by Rechinan** [comment]
Never mind i see that stray pound sign beside webhook now, commencing facepalm. Sorry
