### ISSUE TITLE
No module named queue

### ISSUE THREAD

**Issue by spoothead656** [Brideau/pokelyzer#53]
Trying to get everything all set up and I'm running into this problem. I don't super know what I'm doing, but I've been following the instructions [here](https://github.com/Brideau/pokelyzer/wiki/Windows-Setup-Instructions) and got to the point where I run the server, I guess. When I try though it says "No module named queue." I type "pip install queue" and nothing happens when I start the process over. I'm on Windows 10 if it helps.
![pokelyzer_problem](https://cloud.githubusercontent.com/assets/20803799/17347252/d2fb0ece-58dc-11e6-8f87-b59b8faa1008.png)

**Comment by Brideau** [comment]
Looks like you might have installed Python 3 instead of 2: http://stackoverflow.com/questions/29687837/queue-importerror-in-python-3

They are still making the transition between the two, and lots of people still write software in 2.

**Comment by spoothead656** [comment]
Thanks for the response. I'm using version 2.7.12, the one linked in the how to guide.

**Comment by Brideau** [comment]
I would try downloading the develop branch again using the same link. Sometimes it goes wonky in the middle of the day.

Also, can you double check that there isn't another version of python running on your machine? Just type `python --version` and double check because sometimes strange things happen.

**Comment by Tomatocannon** [comment]
Hi there,

I have the same error. Checked my version with `python --version` and it said I have version 2.7.12 installed.

**Comment by Brideau** [comment]
@Tomatocannon @spoothead656 You might have to go ask the team over at PokemonGo-Map as I'm not all that familiar with their code: https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by Tomatocannon** [comment]
@Brideau Thank you for the fast reply. On a side note: when running the 'setup.bat' file from the Easy-Setup folder I get the following error: `Command "python setup.py egg_info" failed with error code 1`

Maybe this has something to do with it?

**Comment by Brideau** [comment]
Wish I could help, but like I said that isn't my code so I'm not the best person to ask :)

**Comment by Brideau** [comment]
@Tomatocannon BTW: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3086
