### ISSUE TITLE
Can't run listener "Cannot find module bunyan"

### ISSUE THREAD

**Issue by ghost** [Brideau/pokelyzer#56]
I got through everything up until its says to run "node app.js | bunyan -l info".
I get this as a result: 
![image](https://cloud.githubusercontent.com/assets/11514435/17351874/ffb24520-58f7-11e6-9cea-52cfc6ec97c3.png)

**Comment by maxwell-gregory** [comment]
Did you skip this step? `sudo npm install -g bunyan`

**Comment by ghost** [comment]
That sure would be stupid of me to do, but no, I didn't skip that step. That was actually my first attempt to troubleshoot it but that's not whats causing the problem.

**Comment by maxwell-gregory** [comment]
Does it run without bunyan? just remove the `| bunyan -l info`
Don't forget the DB variables in front of it

**Comment by ghost** [comment]
Tried it and got the same error code, this doesn't make much sense
![image](https://cloud.githubusercontent.com/assets/11514435/17354235/3d7ca5f8-590c-11e6-81eb-1d179b2a6038.png)

**Comment by maxwell-gregory** [comment]
Oh ya I forgot that bunyan is in the app too. It is literally just an issue installing bunyan properly.  try running this again:

```
npm install
sudo npm install -g bunyan
```

Make sure you run `npm install` inside the repository

**Comment by ghost** [comment]
No luck, same error every time

**Comment by Brideau** [comment]
Bunyan's causing me a ton of headaches on Windows machines. I'm just going to strip it out altogether.

**Comment by Brideau** [comment]
When your logging library causes more errors than you solve, ditch it. I just pushed a change that removed Bunyan, so hopefully that solves your issue.
