### ISSUE TITLE
Missing Name Column

### ISSUE THREAD

**Issue by maxwell-gregory** [Brideau/pokelyzer#57]
Looks like my restore didn't generate a name column. Shouldn't I see the name column in the log when I restore?
I downloaded the most up to date backup however the new one I restored does not have this line: `pg_restore: creating INDEX "public.name_index"` and thusly no column either

**Comment by maxwell-gregory** [comment]
@Brideau I don't know if this is a bug with your new backup.tar however I went ahead and generated csv of names/ids, imported it to new table, then ran a left join on the ids to get Pokemon names in Tableau. I attached the CSV in case this needs fixing [pokes.csv.zip](https://github.com/Brideau/pokelyzer/files/398760/pokes.csv.zip)

**Comment by Brideau** [comment]
Hmm, the backup _was_ missing the "rarity" column that I recently added, but the pokemon_info table does have the name column. 

Perhaps try again with the version I just uploaded. I just restored it a couple times to double check and had the same result twice.

**Comment by ghost** [comment]
Do you talk about the table 'spotted_pokemon' or 'pokemon_info'
Because the 'spotted_pokemon' doesnt have the Name column anymore. Its only in 'pokemon_info'

**Comment by Brideau** [comment]
Yes that's an intentional design change to follow best-practice for dimensional modeling. I have a brief explanation in my [most recent blog post](http://www.whackdata.com/2016/08/02/find-pokemon-by-rarity-pokelyzer/) but basically it makes maintaining the dataset long-term significantly easier with a very small bit of added complexity.

**Comment by rayuki** [comment]
ok so if its been moved, how do we add it now if following your example first tutorials for tableau? you suggest "Finally, drag the Name dimension into the Pages pane." except we dont have a names dimension now in spotted_pokemon. can we add it another way?

edit: nvm i just read your latest blog post. i just dragged over ID and then overwrote it with name from pokemon_info. all good :+1:

**Comment by Brideau** [comment]
You just have to use the one in `pokemon_info` instead, and if that table isn't showing up, just join it on the Data Sources page the exact same way as the other two.

**Comment by Brideau** [comment]
@NoMotion It ok for me to close this?

**Comment by maxwell-gregory** [comment]
Yea you answered my question and closed it already haha. I just got the new pokemon_info table and joined it
