### ISSUE TITLE
[Idea] Pokémon Name German translation

### ISSUE THREAD

**Issue by fabianwinda** [Brideau/pokelyzer#58]
I´ve made a small sql batch to add german Pokémon names in the pokemon_info table.

`ALTER TABLE pokemon_info ADD name_de text;
UPDATE pokemon_info SET name_de='Bisasam' WHERE pokemon_id=1;
UPDATE pokemon_info SET name_de='Bisaknosp' WHERE pokemon_id=2;
UPDATE pokemon_info SET name_de='Bisaflor' WHERE pokemon_id=3;
UPDATE pokemon_info SET name_de='Glumanda' WHERE pokemon_id=4;
UPDATE pokemon_info SET name_de='Glutexo' WHERE pokemon_id=5;
UPDATE pokemon_info SET name_de='Glurak' WHERE pokemon_id=6;
UPDATE pokemon_info SET name_de='Schiggy' WHERE pokemon_id=7;
UPDATE pokemon_info SET name_de='Schillok' WHERE pokemon_id=8;
UPDATE pokemon_info SET name_de='Turtok' WHERE pokemon_id=9;
UPDATE pokemon_info SET name_de='Raupy' WHERE pokemon_id=10;
UPDATE pokemon_info SET name_de='Safcon' WHERE pokemon_id=11;
UPDATE pokemon_info SET name_de='Smettbo' WHERE pokemon_id=12;
UPDATE pokemon_info SET name_de='Hornliu' WHERE pokemon_id=13;
UPDATE pokemon_info SET name_de='Kokuna' WHERE pokemon_id=14;
UPDATE pokemon_info SET name_de='Bibor' WHERE pokemon_id=15;
UPDATE pokemon_info SET name_de='Taubsi' WHERE pokemon_id=16;
UPDATE pokemon_info SET name_de='Tauboga' WHERE pokemon_id=17;
UPDATE pokemon_info SET name_de='Tauboss' WHERE pokemon_id=18;
UPDATE pokemon_info SET name_de='Rattfratz' WHERE pokemon_id=19;
UPDATE pokemon_info SET name_de='Rattikarl' WHERE pokemon_id=20;
UPDATE pokemon_info SET name_de='Habitak' WHERE pokemon_id=21;
UPDATE pokemon_info SET name_de='Ibitak' WHERE pokemon_id=22;
UPDATE pokemon_info SET name_de='Rettan' WHERE pokemon_id=23;
UPDATE pokemon_info SET name_de='Arbok' WHERE pokemon_id=24;
UPDATE pokemon_info SET name_de='Pikachu' WHERE pokemon_id=25;
UPDATE pokemon_info SET name_de='Raichu' WHERE pokemon_id=26;
UPDATE pokemon_info SET name_de='Sandan' WHERE pokemon_id=27;
UPDATE pokemon_info SET name_de='Sandamer' WHERE pokemon_id=28;
UPDATE pokemon_info SET name_de='Nidoran♀' WHERE pokemon_id=29;
UPDATE pokemon_info SET name_de='Nidorina' WHERE pokemon_id=30;
UPDATE pokemon_info SET name_de='Nidoqueen' WHERE pokemon_id=31;
UPDATE pokemon_info SET name_de='Nidoran♂' WHERE pokemon_id=32;
UPDATE pokemon_info SET name_de='Nidorino' WHERE pokemon_id=33;
UPDATE pokemon_info SET name_de='Nidoking' WHERE pokemon_id=34;
UPDATE pokemon_info SET name_de='Piepi' WHERE pokemon_id=35;
UPDATE pokemon_info SET name_de='Pixi' WHERE pokemon_id=36;
UPDATE pokemon_info SET name_de='Vulpix' WHERE pokemon_id=37;
UPDATE pokemon_info SET name_de='Vulnona' WHERE pokemon_id=38;
UPDATE pokemon_info SET name_de='Pummeluff' WHERE pokemon_id=39;
UPDATE pokemon_info SET name_de='Knuddeluff' WHERE pokemon_id=40;
UPDATE pokemon_info SET name_de='Zubat' WHERE pokemon_id=41;
UPDATE pokemon_info SET name_de='Golbat' WHERE pokemon_id=42;
UPDATE pokemon_info SET name_de='Myrapla' WHERE pokemon_id=43;
UPDATE pokemon_info SET name_de='Duflor' WHERE pokemon_id=44;
UPDATE pokemon_info SET name_de='Giflor' WHERE pokemon_id=45;
UPDATE pokemon_info SET name_de='Paras' WHERE pokemon_id=46;
UPDATE pokemon_info SET name_de='Parasek' WHERE pokemon_id=47;
UPDATE pokemon_info SET name_de='Bluzuk' WHERE pokemon_id=48;
UPDATE pokemon_info SET name_de='Omot' WHERE pokemon_id=49;
UPDATE pokemon_info SET name_de='Digda' WHERE pokemon_id=50;
UPDATE pokemon_info SET name_de='Digdri' WHERE pokemon_id=51;
UPDATE pokemon_info SET name_de='Mauzi' WHERE pokemon_id=52;
UPDATE pokemon_info SET name_de='Snobilikat' WHERE pokemon_id=53;
UPDATE pokemon_info SET name_de='Enton' WHERE pokemon_id=54;
UPDATE pokemon_info SET name_de='Entoron' WHERE pokemon_id=55;
UPDATE pokemon_info SET name_de='Menki' WHERE pokemon_id=56;
UPDATE pokemon_info SET name_de='Rasaff' WHERE pokemon_id=57;
UPDATE pokemon_info SET name_de='Fukano' WHERE pokemon_id=58;
UPDATE pokemon_info SET name_de='Arkani' WHERE pokemon_id=59;
UPDATE pokemon_info SET name_de='Quapsel' WHERE pokemon_id=60;
UPDATE pokemon_info SET name_de='Quaputzi' WHERE pokemon_id=61;
UPDATE pokemon_info SET name_de='Quappo' WHERE pokemon_id=62;
UPDATE pokemon_info SET name_de='Abra' WHERE pokemon_id=63;
UPDATE pokemon_info SET name_de='Kadabra' WHERE pokemon_id=64;
UPDATE pokemon_info SET name_de='Simsala' WHERE pokemon_id=65;
UPDATE pokemon_info SET name_de='Machollo' WHERE pokemon_id=66;
UPDATE pokemon_info SET name_de='Maschock' WHERE pokemon_id=67;
UPDATE pokemon_info SET name_de='Machomei' WHERE pokemon_id=68;
UPDATE pokemon_info SET name_de='Knofensa' WHERE pokemon_id=69;
UPDATE pokemon_info SET name_de='Ultrigaria' WHERE pokemon_id=70;
UPDATE pokemon_info SET name_de='Sarzenia' WHERE pokemon_id=71;
UPDATE pokemon_info SET name_de='Tentacha' WHERE pokemon_id=72;
UPDATE pokemon_info SET name_de='Tentoxa' WHERE pokemon_id=73;
UPDATE pokemon_info SET name_de='Kleinstein' WHERE pokemon_id=74;
UPDATE pokemon_info SET name_de='Georok' WHERE pokemon_id=75;
UPDATE pokemon_info SET name_de='Geowaz' WHERE pokemon_id=76;
UPDATE pokemon_info SET name_de='Ponita' WHERE pokemon_id=77;
UPDATE pokemon_info SET name_de='Gallopa' WHERE pokemon_id=78;
UPDATE pokemon_info SET name_de='Flegmon' WHERE pokemon_id=79;
UPDATE pokemon_info SET name_de='Lahmus' WHERE pokemon_id=80;
UPDATE pokemon_info SET name_de='Magnetilo' WHERE pokemon_id=81;
UPDATE pokemon_info SET name_de='Magneton' WHERE pokemon_id=82;
UPDATE pokemon_info SET name_de='Porenta' WHERE pokemon_id=83;
UPDATE pokemon_info SET name_de='Dodu' WHERE pokemon_id=84;
UPDATE pokemon_info SET name_de='Dodri' WHERE pokemon_id=85;
UPDATE pokemon_info SET name_de='Jurob' WHERE pokemon_id=86;
UPDATE pokemon_info SET name_de='Jugong' WHERE pokemon_id=87;
UPDATE pokemon_info SET name_de='Sleima' WHERE pokemon_id=88;
UPDATE pokemon_info SET name_de='Sleimok' WHERE pokemon_id=89;
UPDATE pokemon_info SET name_de='Muschas' WHERE pokemon_id=90;
UPDATE pokemon_info SET name_de='Austos' WHERE pokemon_id=91;
UPDATE pokemon_info SET name_de='Nebulak' WHERE pokemon_id=92;
UPDATE pokemon_info SET name_de='Alpollo' WHERE pokemon_id=93;
UPDATE pokemon_info SET name_de='Gengar' WHERE pokemon_id=94;
UPDATE pokemon_info SET name_de='Onix' WHERE pokemon_id=95;
UPDATE pokemon_info SET name_de='Traumato' WHERE pokemon_id=96;
UPDATE pokemon_info SET name_de='Hypno' WHERE pokemon_id=97;
UPDATE pokemon_info SET name_de='Krabby' WHERE pokemon_id=98;
UPDATE pokemon_info SET name_de='Kingler' WHERE pokemon_id=99;
UPDATE pokemon_info SET name_de='Voltobal' WHERE pokemon_id=100;
UPDATE pokemon_info SET name_de='Lektrobal' WHERE pokemon_id=101;
UPDATE pokemon_info SET name_de='Owei' WHERE pokemon_id=102;
UPDATE pokemon_info SET name_de='Kokowei' WHERE pokemon_id=103;
UPDATE pokemon_info SET name_de='Tragosso' WHERE pokemon_id=104;
UPDATE pokemon_info SET name_de='Knogga' WHERE pokemon_id=105;
UPDATE pokemon_info SET name_de='Kicklee' WHERE pokemon_id=106;
UPDATE pokemon_info SET name_de='Nockchan' WHERE pokemon_id=107;
UPDATE pokemon_info SET name_de='Schlurp' WHERE pokemon_id=108;
UPDATE pokemon_info SET name_de='Smogon' WHERE pokemon_id=109;
UPDATE pokemon_info SET name_de='Smogmog' WHERE pokemon_id=110;
UPDATE pokemon_info SET name_de='Rihorn' WHERE pokemon_id=111;
UPDATE pokemon_info SET name_de='Rizeros' WHERE pokemon_id=112;
UPDATE pokemon_info SET name_de='Chaneira' WHERE pokemon_id=113;
UPDATE pokemon_info SET name_de='Tangela' WHERE pokemon_id=114;
UPDATE pokemon_info SET name_de='Kangama' WHERE pokemon_id=115;
UPDATE pokemon_info SET name_de='Seeper' WHERE pokemon_id=116;
UPDATE pokemon_info SET name_de='Seemon' WHERE pokemon_id=117;
UPDATE pokemon_info SET name_de='Goldini' WHERE pokemon_id=118;
UPDATE pokemon_info SET name_de='Golking' WHERE pokemon_id=119;
UPDATE pokemon_info SET name_de='Sterndu' WHERE pokemon_id=120;
UPDATE pokemon_info SET name_de='Starmie' WHERE pokemon_id=121;
UPDATE pokemon_info SET name_de='Pantimos' WHERE pokemon_id=122;
UPDATE pokemon_info SET name_de='Sichlor' WHERE pokemon_id=123;
UPDATE pokemon_info SET name_de='Rossana' WHERE pokemon_id=124;
UPDATE pokemon_info SET name_de='Elektek' WHERE pokemon_id=125;
UPDATE pokemon_info SET name_de='Magmar' WHERE pokemon_id=126;
UPDATE pokemon_info SET name_de='Pinsir' WHERE pokemon_id=127;
UPDATE pokemon_info SET name_de='Tauros' WHERE pokemon_id=128;
UPDATE pokemon_info SET name_de='Karpador' WHERE pokemon_id=129;
UPDATE pokemon_info SET name_de='Garados' WHERE pokemon_id=130;
UPDATE pokemon_info SET name_de='Lapras' WHERE pokemon_id=131;
UPDATE pokemon_info SET name_de='Ditto' WHERE pokemon_id=132;
UPDATE pokemon_info SET name_de='Evoli' WHERE pokemon_id=133;
UPDATE pokemon_info SET name_de='Aquana' WHERE pokemon_id=134;
UPDATE pokemon_info SET name_de='Blitza' WHERE pokemon_id=135;
UPDATE pokemon_info SET name_de='Flamara' WHERE pokemon_id=136;
UPDATE pokemon_info SET name_de='Porygon' WHERE pokemon_id=137;
UPDATE pokemon_info SET name_de='Amonitas' WHERE pokemon_id=138;
UPDATE pokemon_info SET name_de='Amoroso' WHERE pokemon_id=139;
UPDATE pokemon_info SET name_de='Kabuto' WHERE pokemon_id=140;
UPDATE pokemon_info SET name_de='Kabutops' WHERE pokemon_id=141;
UPDATE pokemon_info SET name_de='Aerodactyl' WHERE pokemon_id=142;
UPDATE pokemon_info SET name_de='Relaxo' WHERE pokemon_id=143;
UPDATE pokemon_info SET name_de='Arktos' WHERE pokemon_id=144;
UPDATE pokemon_info SET name_de='Zapdos' WHERE pokemon_id=145;
UPDATE pokemon_info SET name_de='Lavados' WHERE pokemon_id=146;
UPDATE pokemon_info SET name_de='Dratini' WHERE pokemon_id=147;
UPDATE pokemon_info SET name_de='Dragonir' WHERE pokemon_id=148;
UPDATE pokemon_info SET name_de='Dragoran' WHERE pokemon_id=149;
UPDATE pokemon_info SET name_de='Mewtu' WHERE pokemon_id=150;
UPDATE pokemon_info SET name_de='Mew' WHERE pokemon_id=151;
`

**Comment by Brideau** [comment]
Awesome idea, and thanks for the implementation. I verified that it works and added it to a new directory in the root so that people can apply it.
