### ISSUE TITLE
Suggestion: Save historic data for pokestops with lured status

### ISSUE THREAD

**Issue by jacobk** [Brideau/pokelyzer#6]
It would be great if it was possible to cross reference the spotted pokemons against lured pokestops in proximity of the spawn point.

Edit: It's available from the PokemonGo-Map server.

**Comment by Brideau** [comment]
I'll have a look! Just trying to clear up some bugs and get another tutorial out the door at the moment, but I'll look into it soon.

**Comment by Brideau** [comment]
This has been added to the most recent version of Pokelyzer, as we're now passed data from PokemonGo-Map that indicates whether a pokemon is from a lure or not.
