### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by SirAzrael** [Brideau/pokelyzer#60]
I ran the python runserver.py code in the command prompt, and at first I seemed to be getting some results (it was saying that pokestops and stuff were found and being upserted), but after a couple minutes I started getting this error. I also wasn't getting stuff put into my database, even though it said stuff was being discovered

**Comment by Brideau** [comment]
Can you post screenshots of your error and the commands you're using to run both PokemonGo map and Pokelyzer?

**Comment by SirAzrael** [comment]
Sure. 
![screenshot 2016-08-03 13 23 05](https://cloud.githubusercontent.com/assets/14100781/17375110/ad2121c4-597d-11e6-9297-fa0118f0ea65.png)

![command](https://cloud.githubusercontent.com/assets/14100781/17375119/ba84c780-597d-11e6-8696-3d35b7c00f32.png)

**Comment by Brideau** [comment]
That looks like trouble with PokemonGo-Map, which is separate from this project (we just use them to collect data). You'll have to go ask them on their issues page: https://github.com/AHAAAAAAA/PokemonGo-Map/issues

**Comment by SirAzrael** [comment]
Ok, thanks
