### ISSUE TITLE
Can't run runserver.py

### ISSUE THREAD

**Issue by vinkenaomi** [Brideau/pokelyzer#62]
Hello,

I've been trying to install pokelyzer but i'm stuck at the runserver.py. My pc runs on Windows and i got Python to work, but it won't open runserver.py I've reinstalled it, but that didn't help. When i type it as in the wiki page it gives "no such file or directory" and when i type out the full path it gives an error "no module named queue". I hope someone here can help me out

**Comment by Brideau** [comment]
Hey there, have a look over at the PokemonGo-Map issues page - it looks like some people got it resolved there: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3086
