### ISSUE TITLE
Found Pokemon aren't added to the database - Error running query

### ISSUE THREAD

**Issue by savaloi** [Brideau/pokelyzer#63]
I'm having a problem with PokemonGo-Map actually inserting found pokemon into the pokelyzer 
database.. As you can see in the attached screenshot, I get an error each time it finds a pokemon.. :(

![original](https://cloud.githubusercontent.com/assets/20825757/17383523/b8a38a86-5a19-11e6-8546-45e859975021.jpg)

Everything seems to have installed and compiled etc correctly, but it just won't run that query..
Any ideas? Can you please help me out?

Here's my setup:
I'm running Lubuntu 16.04.1 (32-bit) in VirtualBox

The commandline run for pokelyzer is:
DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='mypass' DB_PORT=5432 WS_PORT=9876 ERA=2 node app.js | bunyan -l info

The commandline run for PokemonGo-Map is:
python runserver.py -a ptc -u pogousername -p pogopassword -l "mycity" -st 25 -H 0.0.0.0 -k mygoogleapikey -wh http://localhost:9876

Thanks for a wonderful tool!

**Comment by Brideau** [comment]
Hey there, I recently changed the method Pokelyzer uses to see if a piece of data is unique or not. Make sure you're using both the most recent version of Pokelyzer, and that you've applied this morning's patch: https://github.com/Brideau/pokelyzer#aug-3-2016

**Comment by savaloi** [comment]
Hey Ryan, thanks for the tip, I'm new to this, so please bear with me. Unfortunately it seems that PokemonGo-Map is now not outputting any data - which is sad..
It keeps stating Upserted 0 pokemon, 0 pokestops, and 0 gyms :(
As referenced in their issues register here:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3406

I guess I'll have to wait until that's fixed to be able to grab data..

**Comment by Brideau** [comment]
Yeah, sadly everyone is blocked out until somebody gets the API sorted out. If or when they do though, it sounds like everything is working for you in theory!
