### ISSUE TITLE
Grunt build fails to run

### ISSUE THREAD

**Issue by angelusnoctis** [Brideau/pokelyzer#64]
"Tell the author that this fails on your systhem:
grunt Build
this is most likely a problem with the pogomap package, not npm itself"

I was following the guide up until the step where i start the server using the command python runserver and so on, then it told me to write npm install if i get asked to run a grunt build first, but after running npm install i get an error message

[Npm Debug.txt](https://github.com/Brideau/pokelyzer/files/400475/Npm.Debug.txt)

**Comment by Brideau** [comment]
Wish I could help, but that's part of the PokemonGo-Map program and not Pokelyzer. Have a look in their issues section to see if they can help https://github.com/AHAAAAAAA/PokemonGo-Map/issues
