### ISSUE TITLE
Pokelyzer not working while using updated PokemonGoMap (Reborn)

### ISSUE THREAD

**Issue by oynek** [Brideau/pokelyzer#65]
Whenever a Pokémon was found while using [the new scanner](https://github.com/PokemonGoMap/PokemonGo-Map) (develop-branch) this error msg occurs:

```
Pokemon with ID 79 found.
Error running query { [error: column "undefined" does not exist]
  name: 'error',
  length: 103,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '413',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3090',
  routine: 'errorMissingColumn' }
```

**Comment by Brideau** [comment]
Hey there, give it a shot with the master branch - it looks like it includes the required webhook commit, and I set it up without issue.

Also double check that you have the newest version of the webhook app and the recent patches to the database. I've seen this error before with older versions.

**Comment by oynek** [comment]
Is master-branch already working? Thought currently only dev-branch has a working scanner.. 

Checked models.py - your commits seem to be already implemented

```
webhook_data = {
                    'encounter_id': b64encode(str(p['encounter_id'])),
                    'spawnpoint_id': p['spawn_point_id'],
                    'pokemon_id': p['pokemon_data']['pokemon_id'],
                    'latitude': p['latitude'],
                    'longitude': p['longitude'],
                    'disappear_time': calendar.timegm(d_t.timetuple()),
                    'last_modified_time': p['last_modified_timestamp_ms'],
                    'time_until_hidden_ms': p['time_till_hidden_ms'],
                    'is_lured': False
                }

                send_to_webhook('pokemon', webhook_data)
```

**Comment by Brideau** [comment]
I tested the master without issue with a fresh install of Pokelyzer. Have you had any luck so far?

**Comment by Brideau** [comment]
Hmm, I'm seeing this error now after it ran without issue for a while. I'll look into it.

**Comment by chuparCh0pper** [comment]
That's how a wrong SQL Command looks like.

`
INSERT INTO spotted_pokemon 
            ( 
                        encounter_id, 
                        last_modified_time, 
                        time_until_hidden_ms, 
                        hidden_time_unix_s, 
                        hidden_time_utc, 
                        spawnpoint_id, 
                        longitude, 
                        latitude, 
                        pokemon_id, 
                        longitude_jittered, 
                        latitude_jittered, 
                        pokemon_go_era 
            ) 
            VALUES 
            ( 
                        'MTc4MzE0NzE2Mw=='::VARCHAR, 
                        UNDEFINED::         BIGINT, 
                        UNDEFINED::         BIGINT, 
                        1470582506::        BIGINT, 
                        '2016-08-07 15:08:26'::timestamp, 
                        'undefined'::VARCHAR, 
                        1.454331::DOUBLE PRECISION, 
                        1.480623::DOUBLE PRECISION, 
                        120::SMALLINT, 
                        1.45429896881396::DOUBLE PRECISION, 
                        1.4805299536743::DOUBLE PRECISION, 
                        2::INTEGER 
            ) 
ON conflict 
            ( 
                        encounter_id, 
                        spawnpoint_id 
            ) 
            do 
UPDATE 
SET    last_modified_time = excluded.last_modified_time, 
       time_until_hidden_ms = excluded.time_until_hidden_ms, 
       hidden_time_unix_s = excluded.hidden_time_unix_s, 
       hidden_time_utc = excluded.hidden_time_utc;
`

**Comment by Brideau** [comment]
I was wrong about the master branch - you need to use the develop branch. Running the develop branch, I'm having a hard time getting this error to show up consistently.

It was being caused by the missing fields for `last_modified_time` and `time_until_hidden_ms`, which weren't in the master branch webhook, but they exist in develop.

Since switching to develop, I saw the error initial but can no longer create it. Will keep you posted...

**Comment by pperle** [comment]
A not workling SQL Statement looks somethign like this (I inserted mock GPS data)

``` SQL
INSERT INTO spotted_pokemon 
            ( 
                        encounter_id, 
                        last_modified_time, 
                        time_until_hidden_ms, 
                        hidden_time_unix_s, 
                        hidden_time_utc, 
                        spawnpoint_id, 
                        longitude, 
                        latitude, 
                        pokemon_id, 
                        longitude_jittered, 
                        latitude_jittered, 
                        pokemon_go_era 
            ) 
            VALUES 
            ( 
                        'MTc4MzE0NzE2Mw=='::VARCHAR, 
                        UNDEFINED::         BIGINT, 
                        UNDEFINED::         BIGINT, 
                        1470582506::        BIGINT, 
                        '2016-08-07 15:08:26'::timestamp, 
                        'undefined'::VARCHAR, 
                        1.454331::DOUBLE PRECISION, 
                        1.480623::DOUBLE PRECISION, 
                        120::SMALLINT, 
                        1.45429896881396::DOUBLE PRECISION, 
                        1.4805299536743::DOUBLE PRECISION, 
                        2::INTEGER 
            ) 
ON conflict 
            ( 
                        encounter_id, 
                        spawnpoint_id 
            ) 
            do 
UPDATE 
SET    last_modified_time = excluded.last_modified_time, 
       time_until_hidden_ms = excluded.time_until_hidden_ms, 
       hidden_time_unix_s = excluded.hidden_time_unix_s, 
       hidden_time_utc = excluded.hidden_time_utc;
```

> It was being caused by the missing fields for last_modified_time and time_until_hidden_ms, which weren't in the master branch webhook, but they exist in develop.

Looks like spawnpoint_id is also undefined.

**Comment by Brideau** [comment]
@chuparCh0pper Just noticed that myself when using the master branch of PokemonGo-Map because it is missing those fields in the webhook, but it works with develop. Can you try installing PokemonGo-Map with `git clone -b develop https://github.com/PokemonGoMap/PokemonGo-Map.git` and let me know if it works?

**Comment by Brideau** [comment]
OK, just got it to occur again when using the develop branch. Here's what I've noticed so far. When it works, the webhook itself sends the following data (which I manually logged in the console of PokemonGo-Map):

```
{'message': 
  {'time_until_hidden_ms': 238979,
   'last_modified_time': 1470583312369L,
   'disappear_time': 1470583551,
   'pokemon_id': 16,
   'latitude': 46.999057305083156, 
   'spawnpoint_id': u'4ca22075845',
   'is_lured': False,
   'encounter_id': 'MTIyODEyOTgwNDIwMzgzMTczMDk=',
   'longitude': -65.5667284598121}, 
   'type': 'pokemon'}
```

When it doesn't work, it looks like this:

```
{'message': 
   {'disappear_time': 1470583528,
   'pokemon_id': 17, 
   'longitude': -65.573509,
   'latitude': 47.004626,
   'is_lured': True,
   'encounter_id': 'MTg0NDY3NDQwNzE3OTMwNDM5NDE='}, 
   'type': 'pokemon'}
```

So it looks like the lured Pokemon aren't being sent with the same data. I'll put a temporary patch up in Pokelyzer and do a pull request to fix PokemonGo-Map.

**Comment by Brideau** [comment]
OK, I just pushed a temporary fix to the main branch of Pokelyzer. Try the newest version and let me know how it goes. I'll get to work on fixing PokemonGo-Map properly.

**Comment by pperle** [comment]
@Brideau Are you just ignoring all lured pokemons?

**Comment by Brideau** [comment]
Temporarily because they aren't being sent with the correct data. Hopefully it won't take long to fix - sorry for the inconvenience.

**Comment by Brideau** [comment]
I'll be looking to add a new column to pokelyzer as well with a lured/not lured status too.

**Comment by pperle** [comment]
I created a pull request for PokemonGo-Map which fixes the issue.
https://github.com/PokemonGoMap/PokemonGo-Map/pull/33

**Comment by Brideau** [comment]
Unfortunately the fields that are produced for pokemon by the lures aren't the same as when they spawn at a regular spawn point. The 'time until hidden' doesn't exist at all, in fact. I'm going to patch up the listener to deal with this as well.

**Comment by Tuumi** [comment]
Having indications whether it was lured or not would be actually pretty grand.. Plotting data to map aint useful if there's lured pokemons that screw up the 'cleaness' of the data.. Since those pokemons aint native and spawn far more often than possible native pokemons..

**Comment by Brideau** [comment]
@Tuumi Workin on it :)

**Comment by Brideau** [comment]
@chuparCh0pper Can you delete the pull request you have? I don't want to cause any confusion with the one I'm about to make.

**Comment by Brideau** [comment]
@Tuumi Added the lured column and updated the webhook listener to support it: https://github.com/Brideau/pokelyzer/wiki/Patches#aug-7-2016

Until my pull request goes through, anybody having the above issue will have to use my fork for the PokemonGo-Map: https://github.com/Brideau/PokemonGo-Map/tree/patch-1

`git clone -b patch-1 https://github.com/Brideau/PokemonGo-Map/`

**Comment by hryuk** [comment]
Still not working, i think the fix to PokemonGo-Map is broken, syntax issue. Also, i tried to modify the patch fixing the syntax but didn't work anyway.

**Comment by Brideau** [comment]
Yep, I messed it up. Do another pull now of the patch-1 branch on my fork and it should work.

**Comment by hryuk** [comment]
Still not working for me with the updated patch.

`Error running query { [error: syntax error at or near "ON"]
  name: 'error',
  length: 85,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '864',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1044',
  routine: 'scanner_yyerror' }`

**Comment by Brideau** [comment]
@hzeroo Have you done a recent pull of Pokelyzer too?

**Comment by hryuk** [comment]
Yep, and droped the db and restored form latest updated backup.

**Comment by Brideau** [comment]
I stripped out the logging library I was using, but can you stick `console.log(query_string)` just above where it currently says `console.log("Pokemon with ID " + m.pokemon_id + " found.")` and post the output?

**Comment by Brideau** [comment]
I have to run for a few hours so I can't get to this right away, but that error is a syntax error in the SQL query. Logging the above will print out the query so that I can help debug it, as I can't reproduce it at the moment myself.

**Comment by hryuk** [comment]
The query seems right:

`INSERT INTO spotted_pokemon ( encounter_id, last_modified_time, time_until_hidden_ms, hidden_time_unix_s, hidden_time_utc, spawnpoint_id, longitude, latitude, pokemon_id, longitude_jittered, latitude_jittered, pokemon_go_era, lured) VALUES ( '12180414003612262269'::text, 1470595590395::bigint, 817281::bigint, 1470596407::bigint, '2016-08-07 19:00:07'::timestamp, '0d2589c848f'::text, -8.7128899436514::double precision, 42.2016447036293::double precision, 23::smallint, -8.712603993295973::double precision, 42.202050108576614::double precision, 2::integer, 'Not Lured'::text ) ON CONFLICT (encounter_id, spawnpoint_id) DO UPDATE SET last_modified_time = EXCLUDED.last_modified_time, time_until_hidden_ms = EXCLUDED.time_until_hidden_ms, hidden_time_unix_s = EXCLUDED.hidden_time_unix_s, hidden_time_utc = EXCLUDED.hidden_time_utc;`

And the column table definition:

![asdf](https://i.imgur.com/qImAIlb.png)

Will try to find out the problem.

**Comment by Brideau** [comment]
If you copy and paste that query into pgAdmin and execute it, does it work?

**Comment by oynek** [comment]
Finally got it working again. PokemonGo-Map fills database with found Pokémon. But PokemonGo-Map finds monsters where it doesn't even look for (beside these tiny green beehives). 

This results in database entries without proper "time_until_hidden_ms" or "spawnpoint_id".

Any ideas?

Edit: Last column shows "Lured/Not lured".. maybe due to this?

**Comment by hryuk** [comment]
Ok, my problem was caused by a oldest postgree installation that didn't support ON CONFLICT, updating solved it, so is working right now.

**Comment by Brideau** [comment]
@oynek The newest version of PokemonGo-Map returns both "lured" and "wild" pokemon. The "lured" ones are associated with a pokestop, so it's likely that the pokestop itself is within the search zone, but the lured pokemon associated with it are outside of the zone. You can filter based on the "lured" column to hide or show these pokemon.

@hzeroo Ahhh, I forgot about that issue. I've seen it a few times before: "ON CONFLICT" is new in 9.5. Glad to hear things are working now.
