### ISSUE TITLE
Id Primary Key error?

### ISSUE THREAD

**Issue by afairgiant** [Brideau/pokelyzer#66]
I did a fresh install of pokelyzer and ran update on my databse. I'm also running the latest dev version of the pokemap but I'm getting this error when it receives a pokemon from the webhook.

```
Pokemon with ID 41 found.
Error running query { [error: duplicate key value violates unique constraint "id_primary_key"]
  name: 'error',
  length: 194,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(1080) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'spotted_pokemon',
  column: undefined,
  dataType: undefined,
  constraint: 'id_primary_key',
  file: 'nbtinsert.c',
  line: '424',
  routine: '_bt_check_unique' }

```

**Comment by Brideau** [comment]
Very strange. The id column is automatically incremented and the listener doesn't attempt to set it itself, so I'm not sure how this could occur. Can you provide some more details about the parameters being used to run app.js? What version of Postgres are you using?

**Comment by Brideau** [comment]
It looks like this sometimes occurs when a restore has happened multiple times for a database, and it loses track of the sequence number. Give this a try:

SELECT pg_catalog.setval(pg_get_serial_sequence('spotted_pokemon', 'id'), (SELECT MAX(id) FROM spotted_pokemon)+1);

That should reset the sequence number to start after the largest one you currently have.

**Comment by afairgiant** [comment]
It looks like that worked! thank you very much!

**Comment by Brideau** [comment]
Great to hear!
