### ISSUE TITLE
Trouble with new PokemonGo-Map and database

### ISSUE THREAD

**Issue by teknicsrx7** [Brideau/pokelyzer#67]
My database had been working before the shutdown, 3k+ logged. I never made the switch to the updated webhook.

Setup the newest PokemonGo-Map just now, everything fine on that end however i cant seem to add any entries to my database anymore. I did see you just posted a patch about 10mins ago, i downloaded and extracted that zip overwriting the old files. Still no database updates, is there something I'm missing? I did the set DB_NAME etc properly.

Sorry im a bit fresh around here, only really dabble in this stuff

**Comment by Brideau** [comment]
Hey there, there's been a ton of updates since the webhook receiver was released so it might be a hard upgrading process at this point. The data is probably quite stale now since all the game changes anyway, so it might just be worth doing a fresh install at this point. In the long-run, the webhook receiver will make things a lot easier for everyone.

If you _do_ want to retain your data, you'll have to perform all the patches in order starting at the one following the date you originally installed Pokelyzer. I know that's not ideal, but unfortunately nobody has solved the database version control problem the way git has for code.

**Comment by teknicsrx7** [comment]
alright so just do a completely fresh install as if I've never installed it before?

**Comment by Brideau** [comment]
Exactly. The instructions have been updated in the Github wiki so have a look there: https://github.com/Brideau/pokelyzer/wiki

**Comment by Brideau** [comment]
I'd hold off on this for a bit...things are broken right now and I'm trying to fix them.

**Comment by Brideau** [comment]
OK, things are good again. Sorry about that. I made a dumb error.

**Comment by teknicsrx7** [comment]
im actually having a weird issue with password authentication on my database, whenever it upserts a pokemon i get a password authentication error for pokemon_go_role, i must have missed something stupid. ive tried changing the pw in pgadmin3, then i reopen and set db_pass to the same thing and no luck. but I feel like im getting closer at least

it seems im not actually setting my db_pass correctly, i tried changing DB_USER and that didnt change so im assuming i should be editing it somehow other than typing 'set DB_USER=whatever', i type this into a CMD terminal in the pokelyzer directory right?

**Comment by Brideau** [comment]
What operating system are you on? I've seen this problem come up a few times on Windows when people set the 'postgres' password thinking they were setting the pokemon_go_role user password. Have a close look at the wiki instructions for how to fix that.

**Comment by teknicsrx7** [comment]
im on windows.

Going into pgadmin3 i right-click pokemon_go_role, properties, definitions, type password twice.

I think my actual issue is im not properly setting the DB_PASS for pokelyzer. I tried 'set DB_PASS=12345' in BASH and CMD after trying to upsert pokemon it gave me authentication errors. So i tried 'set DB_USER=pokemon_go_role2' and it still says its trying to login to 'pokemon_go_role'. So im not updated the config properly, but not sure how else i should be doing it.

**Comment by teknicsrx7** [comment]
So that was literally my issue, I was not setting DB_PASS, i dont know why it wasnt setting. i was typing the commands correctly and in correct folder.

But i went in an edited to this
`password: process.env.DB_PASS || 'palace'`

where my pass is "palace" and it logs in fine and records the pokemon.

**Comment by Brideau** [comment]
It's been really hard getting things to run similarly on Windows and other operating systems. I'm going to try putting everything in a Docker container soon so that things are consistent across platforms, which will hopefully simplify things in the long-run.

**Comment by teknicsrx7** [comment]
Yea it's working flawlessly now after I did that edit, (besides the lured bug you issued a PR for, as I didn't pull your fork) so for it to work on Windows you'd just need to find a way to properly do the "set DB_xxxx" commands. Other than that I'm logging it perfectly and loving the changes since pre-webhooks

**Comment by teknicsrx7** [comment]
So just to add this on, just bought a new computer so went thru and installed everything, this time I just edited config.js directly with my info and it worked perfectly. Didn't try the batch file but will when I get home and report back.

**Comment by EmpireRoman** [comment]
@Brideau I checked out your config file, would there need to be a ";" right after the password segment?
