### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by Azzivo** [Brideau/pokelyzer#7]
Hello!
The instruction seem fairly a bit off. 
Although I am thankful for them, but I'd recommend running a fresh OS and noting down all the steps. I simply got the step 3-4 of the 2nd part and just stayed stuck there for an hour.

http://i.azzivo.com/2016/07/LockApp_2016-07-28_19-53-29.png

**Comment by Brideau** [comment]
I'm pm the author and let him know you're having some issues. Can you describe exactly what's happening?

**Comment by Brideau** [comment]
I've been updating https://github.com/Brideau/pokelyzer/wiki/Windows-Setup-Instructions with improved instructions. If that doesn't fix your problem, feel free to open this ticket back up.

**Comment by Azzivo** [comment]
The version of PostgreSql allows us to add to the package easily via an inbuilt application stack builder. Go to “All Programs” select PostgreSql and select “Application Stack Builder” then select your database from the drop down menu. Click on the expand button beside “Spatial Extensions” and select the most appropriate PostGIS bundle for your operation system (32bit/64bit)

Next open “PgAdmin III” from “All Programs”. On “Login Roles” right click and select “New Login Role”. In “Role name” type “pokemon_go_role” then select “Role privileges” along the top. Make sure all available check boxes are selected on this time then select “OK”.

The gap between these two steps. 
Once you select your appropriate PostGIS, you need to press next and specify if you want to Skip the installation or go through with it..

No idea what to do, so I tried going through with it, and stayed stuck on it for hours.
