### ISSUE TITLE
No "name" entry on database

### ISSUE THREAD

**Issue by rapinou** [Brideau/pokelyzer#70]
I am trying to configure Power BI like in your wiki, and i have discovered that i have no "name" entry in the database.
Changes since the wiki was published or error somewhere ?
Thanks.

**Comment by Brideau** [comment]
Ah, I need to go update that tutorial since some new changes I've made. The 'name' entry has since been moved into the `pokemon_info` table. You can access it in PowerBI when you join that table to the main `spotted_pokemon` table. Have a look at this in the meantime and hopefully it helps: https://powerbi.microsoft.com/en-us/documentation/powerbi-desktop-create-and-manage-relationships/

**Comment by rapinou** [comment]
Thank you.

PowerBI autodetect relationships between tables during load. I just had to take the name entry in pokemon_info table instead of spotted_pokemon table and it worked \o/

Have another question for the local time plz.
When using label_hh for the spotting by hour graph, it is the utc time which appeared, not the local time. Don't find how to change that on wiki.

**Comment by Brideau** [comment]
Great to hear!

Currently there are two date tables (`date_dimension` and `date_dimension_local`) and two time tables (`time_dimension` and `time_dimension_local`) so just be sure that the auto-detect of PowerBI used the local versions of each.

If that's not the problem, it's also possible that the database timezone is not the same as your time zone. Run `SELECT  current_setting('TIMEZONE');` to confirm.

Let me know if any of these solve the problem. If not, can you post a few rows from your table and let me know your time zone so I can manually check the time values?

**Comment by rapinou** [comment]
Ok, i was using time_dimension instead of time_dimension_local.
My bad, I see wiki, I follow wiki. Next time I will look better to understand operations.
Big thanks, you and your tool are great ! My friends will drool over this map, it will be funny ^^

**Comment by Brideau** [comment]
Glad everything worked out!
