### ISSUE TITLE
pokemon_go_db_backup.tar not usable on Mac

### ISSUE THREAD

**Issue by rdmoore6** [Brideau/pokelyzer#71]
pokemon_go_db_backup.tar downloaded  8 August 16:09 EDT is not usable on Mac. Mac OS Archive Utility silently rejects it; 
"The Unarchiver" (from App store) complains "Data is corrupted"; 
Terminal: roger-mini-local-5:downloads rogermoo$ tar -xvf pokemon_go_db_backupB.tar
tar: Unrecognized archive format

**Comment by wjpvandenheuvel** [comment]
No need to untar the file.  U can restore the tar file itself against the database.
Check the [wiki](https://github.com/Brideau/pokelyzer/wiki/Apple-OS-X-Setup) for more info.

**Comment by Brideau** [comment]
Yep, @freakjam is correct on this: you don't need to extract it. When you go to load it in pgAdmin though, you might need to pick 'All files' from the file dialog menu though, or else it will be greyed out.
