### ISSUE TITLE
Column "undefined" does not exist

### ISSUE THREAD

**Issue by lennon681** [Brideau/pokelyzer#72]
I see there was a recent issue similar to this but it's about a week old which I think is pretty dated with all the changes recently.

I have a PokemonGo-Map setup and running off the dev branch that I pulled just yesterday.  I got the pokelyzer all up and running a minute ago after hard coding my credentials in app.js (the batch and typing by hand wasn't working for me).

I'm now getting data in the table but I'm frequently getting the following error:

Pokemon with ID 41 found.
Pokemon with ID 14 found.
Pokemon with ID 21 found.
Pokemon with ID 19 found.
Pokemon with ID 41 found.
Pokemon with ID 16 found.
Pokemon with ID 21 found.
Pokemon with ID 133 found.
Pokemon with ID 41 found.
Error running query { error: column "undefined" does not exist
    at Connection.parseE (C:\pokeBot\pokelyzer-master2\node_modules\pg\lib\connection.js:551:11)
    at Connection.parseMessage (C:\pokeBot\pokelyzer-master2\node_modules\pg\lib\connection.js:378:17)
    at Socket.<anonymous> (C:\pokeBot\pokelyzer-master2\node_modules\pg\lib\connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  name: 'error',
  length: 103,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '431',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3090',
  routine: 'errorMissingColumn' }
Pokemon with ID 19 found.

**Comment by lennon681** [comment]
Hmm... I changed nothing but literally immediately after posting this I stopped seeing those errors in the messages  dumped...  I'll follow up tomorrow with what it looks like in the morning.

**Comment by acmt** [comment]
If your system is Windows the same error is reported in this thread https://github.com/Brideau/pokelyzer/issues/68

**Comment by lennon681** [comment]
Well it makes no sense to me but it ran all night without issue.

**Comment by acmt** [comment]
What happen when you stop and try start?

**Comment by lennon681** [comment]
No errors after logging about 20.  Before it would be 1-2 then error, 1-2 then error (until it just started working).  Should I also kill and restart PokemonGo Map?

**Comment by Brideau** [comment]
Can you uncomment the line `// console.log(query_string);` around line 100 of app.js and post an example of the output? This will tell me the exact query being sent to the database and make it easier to track down which column is causing the issue.

**Comment by lennon681** [comment]
I could but I'm not seeing the error currently so I don't know if it'd be helpful.  If you want to close this issue that'd be OK with me.  If I have issues again I'll do the step above and either open a new issue or add to #68 if it's still open with the log data.

**Comment by Brideau** [comment]
Sounds good!
