### ISSUE TITLE
Error connecting to the databse

### ISSUE THREAD

**Issue by octave-ati** [Brideau/pokelyzer#73]
Hello,

I get this error after running app.js and the pokemongo map server :

Error fetching client from pool { Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }

I don't know how to fix this, should I open a firewall exception and / or a NAT tunnel for this port?

**Comment by Brideau** [comment]
Can you post the commands you're using to start both PokemonGo-Map and the Pokelyzer webhook listener?

**Comment by octave-ati** [comment]
My bad, I will close this issue, resolved it by manually launching the database using :
postgres -D "mypath" -i -p 5432
