### ISSUE TITLE
When logging out "Pokemon with ID # found."  can you prepend a timestamp?

### ISSUE THREAD

**Issue by martinsweitzer** [Brideau/pokelyzer#75]
When logging out "Pokemon with ID # found."  can you prepend a timestamp?

Just nice to know for one's sanity the last time Pokelyzer received a message

**Comment by Brideau** [comment]
Good idea - I just added it with this commit: https://github.com/Brideau/pokelyzer/commit/a0468f41935cee29c5ae1465a4bf169b8bf8c97c
