### ISSUE TITLE
Error fetching client from pool

### ISSUE THREAD

**Issue by ghost** [Brideau/pokelyzer#76]
I can get it to start and everything works fine but as soon as I start the map itself I get this error that keeps on repeating itself over and over.
![ba9cca3e16f74990bc72cd6435fa5a70](https://cloud.githubusercontent.com/assets/11514435/17543643/b219f4fc-5e97-11e6-9d63-74c5905b3b38.png)

**Comment by acmt** [comment]
The same problem here https://github.com/Brideau/pokelyzer/issues/68

**Comment by ghost** [comment]
So I corrected something in the DB setting and now I get: 
![e96a532e03c244f19b81bb35e4dfa85f](https://cloud.githubusercontent.com/assets/11514435/17543888/54bf1c68-5e99-11e6-8d1c-9e96cbd69332.png) instead. This seems like its more specific but I don't really know how to fix it

**Comment by Brideau** [comment]
Are you using the config file to set the password?

**Comment by Brideau** [comment]
That new error looks like you're missing the "lured" column. Have a look at the latest patches in the wiki, and that should solve the problem.

**Comment by FiveWord** [comment]
Installed the patch and now I'm back to the original error

**Comment by FiveWord** [comment]
I think I got everything figured out, but if I'm running multiple workers, do I add -wh localhost:9876 to each of the starting scripts for each worker?

**Comment by ghost** [comment]
Thanks for the help, I had the newest pokelyzer and map but I forgot to update my database in pgadmin, which is what was causing issues.
