### ISSUE TITLE
PokemonMap Changes

### ISSUE THREAD

**Issue by elit3ge** [Brideau/pokelyzer#79]
I'm not sure if this will affect this or not.

https://github.com/PokemonGoMap/PokemonGo-Map/commit/83fab06f4fea54a58d0b0cebb95bed24551037c7

Looks like it removed encountered_id

**Comment by cytec** [comment]
that doesn't affect pokelyzer, the changes where made only for forts see: https://github.com/PokemonGoMap/PokemonGo-Map/blob/83fab06f4fea54a58d0b0cebb95bed24551037c7/pogom/models.py#L329

**Comment by elit3ge** [comment]
Too easy, I can update now :)
