### ISSUE TITLE
Unicode error while logging

### ISSUE THREAD

**Issue by thedavidharris** [Brideau/pokelyzer#8]
Likely the gender symbol for Nidoran

Exception in thread search_thread-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/vagrant/pokelyzer/PokemonGo-Map/pogom/search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/vagrant/pokelyzer/PokemonGo-Map/pogom/models.py", line 253, in parse_map
    logPokemonDb(p)
  File "/vagrant/pokelyzer/PokemonGo-Map/pogom/customLog.py", line 57, in logPokemonDb
    cursor.execute(query, data)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2642' in position 7: ordinal not in range(256)

**Comment by Brideau** [comment]
If you highlight your database in pgAdmin, what's next to Encoding under the Properties tab? Somebody else had this issue earlier because their database was in ASCII encoding and I thought that was an anomaly (all mine default to UTF-8).

What operating system is the database running on?

**Comment by Brideau** [comment]
I believe I've found the culprit. If you're running Windows, the default operating system encoding is ASCII. To fix this, as you create the database, go to the definition tab and for "Encoding" select UTF8. 

I've updates the Windows instructions to reflect this.

**Comment by thedavidharris** [comment]
The error message shows it, Latin-1, and I'm on Ubuntu via Vagrant. It's a postgres error dealing with using the en_US locale when the locale should be en_US.UTF-8, I'm looking into debugging it.

**Comment by thedavidharris** [comment]
I followed this and it worked well enough, this is just on a local instance I'm toying with: http://jes.al/2014/07/fixing-postgresql-local-issues/

For new Ubuntu users might be worth it to tell them to check their locale before installing Postgres, these lines should fix it:

export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

This could also just be an issue with my Vagrant box though.

**Comment by Brideau** [comment]
Thanks for solving that! I'll update the wiki.
